"""UI strings of the integrated player and of live mode (spec 2.6, operator decision Q5).

They live here instead of in video_translator_gui.py so the GUI file does not
grow by thousands of lines; the GUI merges them into UI_STRINGS at import, so
UI_STRINGS stays the single runtime dictionary and App._s keeps its
it -> en -> key fallback. Keys land with the phase that uses them.

Placeholders ({version}, {cmd}, {detail}, {size}, {license}) must be the same
in every language (tests/test_ui_i18n_coverage.py checks it). Brand names
(mpv, libmpv, python-mpv, Vulkan, setup_windows.bat) are not translated.
"""

from __future__ import annotations

PLAYER_UI_STRINGS: dict[str, dict[str, str]] = {
    "it": {
        "player_badge": "Player",
        "player_badge_ok": "Player pronto (mpv {version})",
        "player_unavailable_title": "Player integrato non disponibile",
        "player_missing_pymod": "Il pacchetto python-mpv non è installato.",
        "player_missing_libmpv_linux": "libmpv non è installata. Installala con: {cmd}",
        "player_missing_libmpv_win": "libmpv non è installata. Esegui setup_windows.bat (Repair) oppure installala ora.",
        "player_libmpv_too_old": "La libmpv installata ({version}) è troppo vecchia: serve la 0.34 o successiva.",
        "player_libmpv_load_failed": "Impossibile caricare libmpv ({detail}). Il file potrebbe essere danneggiato o bloccato dall'antivirus.",
        "player_vulkan_missing": "libmpv richiede il runtime Vulkan (vulkan-1.dll): aggiorna il driver grafico o reinstalla il player.",
        "player_probe_crashed": "libmpv si è arrestata in modo anomalo durante il caricamento: il player resta disattivato. Vedi il log.",
        "player_restart_required": "Riavvia l'applicazione per completare l'attivazione del player.",
        "player_install_btn": "Installa player",
        "player_install_confirm": "Scaricare e installare i componenti del player video (circa {size} MB)?",
        "player_installing": "Installazione del player...",
        "player_install_ok": "Player installato.",
        "player_install_failed": "Installazione del player non riuscita: vedi il log.",
        "player_credits": "Riproduzione video: mpv (libmpv), {license}",
        "player_license_system": "libreria di sistema",
        "live_err_busy_install": "È in corso un'installazione: attendi che finisca.",
        "player_playlist_sources": "Sorgenti",
        "player_playlist_results": "Risultati",
    },
    "en": {
        "player_badge": "Player",
        "player_badge_ok": "Player ready (mpv {version})",
        "player_unavailable_title": "Integrated player not available",
        "player_missing_pymod": "The python-mpv package is not installed.",
        "player_missing_libmpv_linux": "libmpv is not installed. Install it with: {cmd}",
        "player_missing_libmpv_win": "libmpv is not installed. Run setup_windows.bat (Repair) or install it now.",
        "player_libmpv_too_old": "The installed libmpv ({version}) is too old: 0.34 or newer is needed.",
        "player_libmpv_load_failed": "libmpv could not be loaded ({detail}). The file may be damaged or blocked by the antivirus.",
        "player_vulkan_missing": "libmpv needs the Vulkan runtime (vulkan-1.dll): update the graphics driver or install the player again.",
        "player_probe_crashed": "libmpv crashed while loading: the player stays disabled. See the log.",
        "player_restart_required": "Restart the application to finish enabling the player.",
        "player_install_btn": "Install player",
        "player_install_confirm": "Download and install the video player components (about {size} MB)?",
        "player_installing": "Installing the player...",
        "player_install_ok": "Player installed.",
        "player_install_failed": "Player installation failed: see the log.",
        "player_credits": "Video playback: mpv (libmpv), {license}",
        "player_license_system": "system library",
        "live_err_busy_install": "An installation is running: wait for it to finish.",
        "player_playlist_sources": "Sources",
        "player_playlist_results": "Results",
    },
    "ar": {
        "player_badge": "المشغل",
        "player_badge_ok": "المشغل جاهز (mpv {version})",
        "player_unavailable_title": "المشغل المدمج غير متاح",
        "player_missing_pymod": "حزمة python-mpv غير مثبتة.",
        "player_missing_libmpv_linux": "مكتبة libmpv غير مثبتة. ثبّتها باستخدام: {cmd}",
        "player_missing_libmpv_win": "مكتبة libmpv غير مثبتة. شغّل setup_windows.bat (Repair) أو ثبّتها الآن.",
        "player_libmpv_too_old": "إصدار libmpv المثبت ({version}) قديم جدًا: يلزم الإصدار 0.34 أو أحدث.",
        "player_libmpv_load_failed": "تعذّر تحميل libmpv ({detail}). قد يكون الملف تالفًا أو محظورًا من برنامج مكافحة الفيروسات.",
        "player_vulkan_missing": "تحتاج libmpv إلى بيئة تشغيل Vulkan (vulkan-1.dll): حدّث برنامج تشغيل الرسومات أو أعد تثبيت المشغل.",
        "player_probe_crashed": "تعطلت libmpv أثناء التحميل: سيبقى المشغل معطّلًا. راجع السجل.",
        "player_restart_required": "أعد تشغيل التطبيق لإكمال تفعيل المشغل.",
        "player_install_btn": "تثبيت المشغل",
        "player_install_confirm": "هل تريد تنزيل مكونات مشغل الفيديو وتثبيتها (حوالي {size} ميغابايت)؟",
        "player_installing": "جارٍ تثبيت المشغل...",
        "player_install_ok": "تم تثبيت المشغل.",
        "player_install_failed": "فشل تثبيت المشغل: راجع السجل.",
        "player_credits": "تشغيل الفيديو: mpv (libmpv)، {license}",
        "player_license_system": "مكتبة النظام",
        "live_err_busy_install": "هناك عملية تثبيت جارية: انتظر حتى تنتهي.",
        "player_playlist_sources": "المصادر",
        "player_playlist_results": "النتائج",
    },
    "zh": {
        "player_badge": "播放器",
        "player_badge_ok": "播放器已就绪 (mpv {version})",
        "player_unavailable_title": "内置播放器不可用",
        "player_missing_pymod": "未安装 python-mpv 软件包。",
        "player_missing_libmpv_linux": "未安装 libmpv。请使用以下命令安装: {cmd}",
        "player_missing_libmpv_win": "未安装 libmpv。请运行 setup_windows.bat (Repair) 或立即安装。",
        "player_libmpv_too_old": "已安装的 libmpv ({version}) 版本过旧: 需要 0.34 或更高版本。",
        "player_libmpv_load_failed": "无法加载 libmpv ({detail})。文件可能已损坏或被杀毒软件拦截。",
        "player_vulkan_missing": "libmpv 需要 Vulkan 运行时 (vulkan-1.dll): 请更新显卡驱动或重新安装播放器。",
        "player_probe_crashed": "libmpv 在加载时崩溃: 播放器保持禁用。请查看日志。",
        "player_restart_required": "请重新启动应用程序以完成播放器的启用。",
        "player_install_btn": "安装播放器",
        "player_install_confirm": "是否下载并安装视频播放器组件 (约 {size} MB)？",
        "player_installing": "正在安装播放器...",
        "player_install_ok": "播放器已安装。",
        "player_install_failed": "播放器安装失败: 请查看日志。",
        "player_credits": "视频播放: mpv (libmpv), {license}",
        "player_license_system": "系统库",
        "live_err_busy_install": "正在进行安装: 请等待其完成。",
        "player_playlist_sources": "源文件",
        "player_playlist_results": "结果",
    },
    "cs": {
        "player_badge": "Přehrávač",
        "player_badge_ok": "Přehrávač je připraven (mpv {version})",
        "player_unavailable_title": "Vestavěný přehrávač není k dispozici",
        "player_missing_pymod": "Balíček python-mpv není nainstalován.",
        "player_missing_libmpv_linux": "Knihovna libmpv není nainstalována. Nainstalujte ji příkazem: {cmd}",
        "player_missing_libmpv_win": "Knihovna libmpv není nainstalována. Spusťte setup_windows.bat (Repair) nebo ji nainstalujte nyní.",
        "player_libmpv_too_old": "Nainstalovaná knihovna libmpv ({version}) je příliš stará: je potřeba verze 0.34 nebo novější.",
        "player_libmpv_load_failed": "Knihovnu libmpv nelze načíst ({detail}). Soubor může být poškozený nebo blokovaný antivirem.",
        "player_vulkan_missing": "Knihovna libmpv vyžaduje běhové prostředí Vulkan (vulkan-1.dll): aktualizujte ovladač grafické karty nebo přehrávač nainstalujte znovu.",
        "player_probe_crashed": "Knihovna libmpv při načítání spadla: přehrávač zůstává vypnutý. Podívejte se do protokolu.",
        "player_restart_required": "Restartujte aplikaci, aby se aktivace přehrávače dokončila.",
        "player_install_btn": "Nainstalovat přehrávač",
        "player_install_confirm": "Stáhnout a nainstalovat součásti videopřehrávače (přibližně {size} MB)?",
        "player_installing": "Instalace přehrávače...",
        "player_install_ok": "Přehrávač byl nainstalován.",
        "player_install_failed": "Instalace přehrávače selhala: podívejte se do protokolu.",
        "player_credits": "Přehrávání videa: mpv (libmpv), {license}",
        "player_license_system": "systémová knihovna",
        "live_err_busy_install": "Probíhá instalace: počkejte, až skončí.",
        "player_playlist_sources": "Zdroje",
        "player_playlist_results": "Výsledky",
    },
    "da": {
        "player_badge": "Afspiller",
        "player_badge_ok": "Afspilleren er klar (mpv {version})",
        "player_unavailable_title": "Den indbyggede afspiller er ikke tilgængelig",
        "player_missing_pymod": "Pakken python-mpv er ikke installeret.",
        "player_missing_libmpv_linux": "libmpv er ikke installeret. Installer det med: {cmd}",
        "player_missing_libmpv_win": "libmpv er ikke installeret. Kør setup_windows.bat (Repair), eller installer det nu.",
        "player_libmpv_too_old": "Den installerede libmpv ({version}) er for gammel: version 0.34 eller nyere kræves.",
        "player_libmpv_load_failed": "libmpv kunne ikke indlæses ({detail}). Filen kan være beskadiget eller blokeret af antivirusprogrammet.",
        "player_vulkan_missing": "libmpv kræver Vulkan-runtime (vulkan-1.dll): opdater grafikdriveren, eller installer afspilleren igen.",
        "player_probe_crashed": "libmpv gik ned under indlæsningen: afspilleren forbliver deaktiveret. Se loggen.",
        "player_restart_required": "Genstart programmet for at fuldføre aktiveringen af afspilleren.",
        "player_install_btn": "Installer afspiller",
        "player_install_confirm": "Vil du downloade og installere videoafspillerens komponenter (ca. {size} MB)?",
        "player_installing": "Installerer afspilleren...",
        "player_install_ok": "Afspilleren er installeret.",
        "player_install_failed": "Installationen af afspilleren mislykkedes: se loggen.",
        "player_credits": "Videoafspilning: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installation er i gang: vent, til den er færdig.",
        "player_playlist_sources": "Kilder",
        "player_playlist_results": "Resultater",
    },
    "nl": {
        "player_badge": "Speler",
        "player_badge_ok": "Speler gereed (mpv {version})",
        "player_unavailable_title": "Ingebouwde speler niet beschikbaar",
        "player_missing_pymod": "Het pakket python-mpv is niet geïnstalleerd.",
        "player_missing_libmpv_linux": "libmpv is niet geïnstalleerd. Installeer het met: {cmd}",
        "player_missing_libmpv_win": "libmpv is niet geïnstalleerd. Voer setup_windows.bat (Repair) uit of installeer het nu.",
        "player_libmpv_too_old": "De geïnstalleerde libmpv ({version}) is te oud: versie 0.34 of nieuwer is vereist.",
        "player_libmpv_load_failed": "libmpv kon niet worden geladen ({detail}). Het bestand is mogelijk beschadigd of geblokkeerd door de antivirus.",
        "player_vulkan_missing": "libmpv heeft de Vulkan-runtime nodig (vulkan-1.dll): werk het grafische stuurprogramma bij of installeer de speler opnieuw.",
        "player_probe_crashed": "libmpv is vastgelopen tijdens het laden: de speler blijft uitgeschakeld. Zie het logboek.",
        "player_restart_required": "Start de applicatie opnieuw om het inschakelen van de speler te voltooien.",
        "player_install_btn": "Speler installeren",
        "player_install_confirm": "De onderdelen van de videospeler downloaden en installeren (ongeveer {size} MB)?",
        "player_installing": "Speler wordt geïnstalleerd...",
        "player_install_ok": "Speler geïnstalleerd.",
        "player_install_failed": "Installatie van de speler mislukt: zie het logboek.",
        "player_credits": "Videoweergave: mpv (libmpv), {license}",
        "player_license_system": "systeembibliotheek",
        "live_err_busy_install": "Er loopt een installatie: wacht tot deze klaar is.",
        "player_playlist_sources": "Bronnen",
        "player_playlist_results": "Resultaten",
    },
    "fi": {
        "player_badge": "Soitin",
        "player_badge_ok": "Soitin on valmis (mpv {version})",
        "player_unavailable_title": "Sisäänrakennettu soitin ei ole käytettävissä",
        "player_missing_pymod": "python-mpv-pakettia ei ole asennettu.",
        "player_missing_libmpv_linux": "libmpv-kirjastoa ei ole asennettu. Asenna se komennolla: {cmd}",
        "player_missing_libmpv_win": "libmpv-kirjastoa ei ole asennettu. Suorita setup_windows.bat (Repair) tai asenna se nyt.",
        "player_libmpv_too_old": "Asennettu libmpv ({version}) on liian vanha: tarvitaan versio 0.34 tai uudempi.",
        "player_libmpv_load_failed": "libmpv-kirjastoa ei voitu ladata ({detail}). Tiedosto voi olla vioittunut tai virustorjunnan estämä.",
        "player_vulkan_missing": "libmpv tarvitsee Vulkan-ajonaikaisympäristön (vulkan-1.dll): päivitä näytönohjaimen ajuri tai asenna soitin uudelleen.",
        "player_probe_crashed": "libmpv kaatui latauksen aikana: soitin pysyy poissa käytöstä. Katso loki.",
        "player_restart_required": "Käynnistä sovellus uudelleen, jotta soittimen käyttöönotto valmistuu.",
        "player_install_btn": "Asenna soitin",
        "player_install_confirm": "Ladataanko ja asennetaanko videosoittimen osat (noin {size} Mt)?",
        "player_installing": "Asennetaan soitinta...",
        "player_install_ok": "Soitin asennettu.",
        "player_install_failed": "Soittimen asennus epäonnistui: katso loki.",
        "player_credits": "Videotoisto: mpv (libmpv), {license}",
        "player_license_system": "järjestelmäkirjasto",
        "live_err_busy_install": "Asennus on käynnissä: odota, että se valmistuu.",
        "player_playlist_sources": "Lähteet",
        "player_playlist_results": "Tulokset",
    },
    "fr": {
        "player_badge": "Lecteur",
        "player_badge_ok": "Lecteur prêt (mpv {version})",
        "player_unavailable_title": "Lecteur intégré indisponible",
        "player_missing_pymod": "Le paquet python-mpv n'est pas installé.",
        "player_missing_libmpv_linux": "libmpv n'est pas installée. Installez-la avec : {cmd}",
        "player_missing_libmpv_win": "libmpv n'est pas installée. Lancez setup_windows.bat (Repair) ou installez-la maintenant.",
        "player_libmpv_too_old": "La libmpv installée ({version}) est trop ancienne : la version 0.34 ou plus récente est requise.",
        "player_libmpv_load_failed": "Impossible de charger libmpv ({detail}). Le fichier est peut-être endommagé ou bloqué par l'antivirus.",
        "player_vulkan_missing": "libmpv a besoin du runtime Vulkan (vulkan-1.dll) : mettez à jour le pilote graphique ou réinstallez le lecteur.",
        "player_probe_crashed": "libmpv a planté pendant le chargement : le lecteur reste désactivé. Consultez le journal.",
        "player_restart_required": "Redémarrez l'application pour terminer l'activation du lecteur.",
        "player_install_btn": "Installer le lecteur",
        "player_install_confirm": "Télécharger et installer les composants du lecteur vidéo (environ {size} Mo) ?",
        "player_installing": "Installation du lecteur...",
        "player_install_ok": "Lecteur installé.",
        "player_install_failed": "L'installation du lecteur a échoué : consultez le journal.",
        "player_credits": "Lecture vidéo : mpv (libmpv), {license}",
        "player_license_system": "bibliothèque système",
        "live_err_busy_install": "Une installation est en cours : attendez qu'elle se termine.",
        "player_playlist_sources": "Sources",
        "player_playlist_results": "Résultats",
    },
    "de": {
        "player_badge": "Player",
        "player_badge_ok": "Player bereit (mpv {version})",
        "player_unavailable_title": "Integrierter Player nicht verfügbar",
        "player_missing_pymod": "Das Paket python-mpv ist nicht installiert.",
        "player_missing_libmpv_linux": "libmpv ist nicht installiert. Installieren Sie es mit: {cmd}",
        "player_missing_libmpv_win": "libmpv ist nicht installiert. Führen Sie setup_windows.bat (Repair) aus oder installieren Sie es jetzt.",
        "player_libmpv_too_old": "Die installierte libmpv ({version}) ist zu alt: Version 0.34 oder neuer wird benötigt.",
        "player_libmpv_load_failed": "libmpv konnte nicht geladen werden ({detail}). Die Datei ist möglicherweise beschädigt oder vom Virenschutz blockiert.",
        "player_vulkan_missing": "libmpv benötigt die Vulkan-Laufzeitumgebung (vulkan-1.dll): Aktualisieren Sie den Grafiktreiber oder installieren Sie den Player erneut.",
        "player_probe_crashed": "libmpv ist beim Laden abgestürzt: Der Player bleibt deaktiviert. Siehe Protokoll.",
        "player_restart_required": "Starten Sie die Anwendung neu, um die Aktivierung des Players abzuschließen.",
        "player_install_btn": "Player installieren",
        "player_install_confirm": "Die Komponenten des Videoplayers herunterladen und installieren (etwa {size} MB)?",
        "player_installing": "Player wird installiert...",
        "player_install_ok": "Player installiert.",
        "player_install_failed": "Installation des Players fehlgeschlagen: siehe Protokoll.",
        "player_credits": "Videowiedergabe: mpv (libmpv), {license}",
        "player_license_system": "Systembibliothek",
        "live_err_busy_install": "Eine Installation läuft: Warten Sie, bis sie abgeschlossen ist.",
        "player_playlist_sources": "Quellen",
        "player_playlist_results": "Ergebnisse",
    },
    "el": {
        "player_badge": "Αναπαραγωγέας",
        "player_badge_ok": "Ο αναπαραγωγέας είναι έτοιμος (mpv {version})",
        "player_unavailable_title": "Ο ενσωματωμένος αναπαραγωγέας δεν είναι διαθέσιμος",
        "player_missing_pymod": "Το πακέτο python-mpv δεν είναι εγκατεστημένο.",
        "player_missing_libmpv_linux": "Η libmpv δεν είναι εγκατεστημένη. Εγκαταστήστε τη με: {cmd}",
        "player_missing_libmpv_win": "Η libmpv δεν είναι εγκατεστημένη. Εκτελέστε το setup_windows.bat (Repair) ή εγκαταστήστε τη τώρα.",
        "player_libmpv_too_old": "Η εγκατεστημένη libmpv ({version}) είναι πολύ παλιά: απαιτείται η έκδοση 0.34 ή νεότερη.",
        "player_libmpv_load_failed": "Δεν ήταν δυνατή η φόρτωση της libmpv ({detail}). Το αρχείο μπορεί να είναι κατεστραμμένο ή να έχει αποκλειστεί από το πρόγραμμα προστασίας από ιούς.",
        "player_vulkan_missing": "Η libmpv χρειάζεται το περιβάλλον εκτέλεσης Vulkan (vulkan-1.dll): ενημερώστε το πρόγραμμα οδήγησης γραφικών ή εγκαταστήστε ξανά τον αναπαραγωγέα.",
        "player_probe_crashed": "Η libmpv κατέρρευσε κατά τη φόρτωση: ο αναπαραγωγέας παραμένει απενεργοποιημένος. Δείτε το ημερολόγιο.",
        "player_restart_required": "Επανεκκινήστε την εφαρμογή για να ολοκληρωθεί η ενεργοποίηση του αναπαραγωγέα.",
        "player_install_btn": "Εγκατάσταση αναπαραγωγέα",
        "player_install_confirm": "Λήψη και εγκατάσταση των στοιχείων του αναπαραγωγέα βίντεο (περίπου {size} MB);",
        "player_installing": "Εγκατάσταση του αναπαραγωγέα...",
        "player_install_ok": "Ο αναπαραγωγέας εγκαταστάθηκε.",
        "player_install_failed": "Η εγκατάσταση του αναπαραγωγέα απέτυχε: δείτε το ημερολόγιο.",
        "player_credits": "Αναπαραγωγή βίντεο: mpv (libmpv), {license}",
        "player_license_system": "βιβλιοθήκη συστήματος",
        "live_err_busy_install": "Εκτελείται μια εγκατάσταση: περιμένετε να ολοκληρωθεί.",
        "player_playlist_sources": "Πηγές",
        "player_playlist_results": "Αποτελέσματα",
    },
    "hi": {
        "player_badge": "प्लेयर",
        "player_badge_ok": "प्लेयर तैयार है (mpv {version})",
        "player_unavailable_title": "अंतर्निहित प्लेयर उपलब्ध नहीं है",
        "player_missing_pymod": "python-mpv पैकेज इंस्टॉल नहीं है।",
        "player_missing_libmpv_linux": "libmpv इंस्टॉल नहीं है। इसे इस कमांड से इंस्टॉल करें: {cmd}",
        "player_missing_libmpv_win": "libmpv इंस्टॉल नहीं है। setup_windows.bat (Repair) चलाएँ या इसे अभी इंस्टॉल करें।",
        "player_libmpv_too_old": "इंस्टॉल की गई libmpv ({version}) बहुत पुरानी है: 0.34 या नया संस्करण आवश्यक है।",
        "player_libmpv_load_failed": "libmpv लोड नहीं हो सकी ({detail})। फ़ाइल क्षतिग्रस्त हो सकती है या एंटीवायरस ने उसे ब्लॉक किया हो सकता है।",
        "player_vulkan_missing": "libmpv को Vulkan रनटाइम (vulkan-1.dll) चाहिए: ग्राफ़िक्स ड्राइवर अपडेट करें या प्लेयर को फिर से इंस्टॉल करें।",
        "player_probe_crashed": "लोड करते समय libmpv क्रैश हो गई: प्लेयर अक्षम रहेगा। लॉग देखें।",
        "player_restart_required": "प्लेयर को सक्षम करने की प्रक्रिया पूरी करने के लिए एप्लिकेशन को पुनः आरंभ करें।",
        "player_install_btn": "प्लेयर इंस्टॉल करें",
        "player_install_confirm": "वीडियो प्लेयर के घटक डाउनलोड और इंस्टॉल करें (लगभग {size} MB)?",
        "player_installing": "प्लेयर इंस्टॉल हो रहा है...",
        "player_install_ok": "प्लेयर इंस्टॉल हो गया।",
        "player_install_failed": "प्लेयर इंस्टॉल नहीं हो सका: लॉग देखें।",
        "player_credits": "वीडियो प्लेबैक: mpv (libmpv), {license}",
        "player_license_system": "सिस्टम लाइब्रेरी",
        "live_err_busy_install": "एक इंस्टॉलेशन चल रहा है: उसके पूरा होने तक प्रतीक्षा करें।",
        "player_playlist_sources": "स्रोत",
        "player_playlist_results": "परिणाम",
    },
    "hu": {
        "player_badge": "Lejátszó",
        "player_badge_ok": "A lejátszó kész (mpv {version})",
        "player_unavailable_title": "A beépített lejátszó nem érhető el",
        "player_missing_pymod": "A python-mpv csomag nincs telepítve.",
        "player_missing_libmpv_linux": "A libmpv nincs telepítve. Telepítse ezzel a paranccsal: {cmd}",
        "player_missing_libmpv_win": "A libmpv nincs telepítve. Futtassa a setup_windows.bat fájlt (Repair), vagy telepítse most.",
        "player_libmpv_too_old": "A telepített libmpv ({version}) túl régi: 0.34-es vagy újabb verzió szükséges.",
        "player_libmpv_load_failed": "A libmpv nem tölthető be ({detail}). Lehet, hogy a fájl sérült, vagy a víruskereső blokkolja.",
        "player_vulkan_missing": "A libmpv-nek szüksége van a Vulkan futtatókörnyezetre (vulkan-1.dll): frissítse a grafikus illesztőprogramot, vagy telepítse újra a lejátszót.",
        "player_probe_crashed": "A libmpv betöltés közben összeomlott: a lejátszó letiltva marad. Nézze meg a naplót.",
        "player_restart_required": "Indítsa újra az alkalmazást a lejátszó bekapcsolásának befejezéséhez.",
        "player_install_btn": "Lejátszó telepítése",
        "player_install_confirm": "Letölti és telepíti a videolejátszó összetevőit (kb. {size} MB)?",
        "player_installing": "A lejátszó telepítése...",
        "player_install_ok": "A lejátszó telepítve.",
        "player_install_failed": "A lejátszó telepítése nem sikerült: nézze meg a naplót.",
        "player_credits": "Videolejátszás: mpv (libmpv), {license}",
        "player_license_system": "rendszerkönyvtár",
        "live_err_busy_install": "Telepítés van folyamatban: várja meg, amíg befejeződik.",
        "player_playlist_sources": "Források",
        "player_playlist_results": "Eredmények",
    },
    "id": {
        "player_badge": "Pemutar",
        "player_badge_ok": "Pemutar siap (mpv {version})",
        "player_unavailable_title": "Pemutar bawaan tidak tersedia",
        "player_missing_pymod": "Paket python-mpv belum terpasang.",
        "player_missing_libmpv_linux": "libmpv belum terpasang. Pasang dengan: {cmd}",
        "player_missing_libmpv_win": "libmpv belum terpasang. Jalankan setup_windows.bat (Repair) atau pasang sekarang.",
        "player_libmpv_too_old": "libmpv yang terpasang ({version}) terlalu lama: diperlukan versi 0.34 atau yang lebih baru.",
        "player_libmpv_load_failed": "libmpv tidak dapat dimuat ({detail}). Berkas mungkin rusak atau diblokir oleh antivirus.",
        "player_vulkan_missing": "libmpv memerlukan runtime Vulkan (vulkan-1.dll): perbarui driver grafis atau pasang ulang pemutar.",
        "player_probe_crashed": "libmpv mengalami crash saat dimuat: pemutar tetap dinonaktifkan. Lihat log.",
        "player_restart_required": "Mulai ulang aplikasi untuk menyelesaikan pengaktifan pemutar.",
        "player_install_btn": "Pasang pemutar",
        "player_install_confirm": "Unduh dan pasang komponen pemutar video (sekitar {size} MB)?",
        "player_installing": "Memasang pemutar...",
        "player_install_ok": "Pemutar terpasang.",
        "player_install_failed": "Pemasangan pemutar gagal: lihat log.",
        "player_credits": "Pemutaran video: mpv (libmpv), {license}",
        "player_license_system": "pustaka sistem",
        "live_err_busy_install": "Sedang ada pemasangan: tunggu hingga selesai.",
        "player_playlist_sources": "Sumber",
        "player_playlist_results": "Hasil",
    },
    "ja": {
        "player_badge": "プレーヤー",
        "player_badge_ok": "プレーヤー準備完了 (mpv {version})",
        "player_unavailable_title": "内蔵プレーヤーは利用できません",
        "player_missing_pymod": "python-mpv パッケージがインストールされていません。",
        "player_missing_libmpv_linux": "libmpv がインストールされていません。次のコマンドでインストールしてください: {cmd}",
        "player_missing_libmpv_win": "libmpv がインストールされていません。setup_windows.bat (Repair) を実行するか、今すぐインストールしてください。",
        "player_libmpv_too_old": "インストールされている libmpv ({version}) は古すぎます: 0.34 以降が必要です。",
        "player_libmpv_load_failed": "libmpv を読み込めませんでした ({detail})。ファイルが破損しているか、ウイルス対策ソフトにブロックされている可能性があります。",
        "player_vulkan_missing": "libmpv には Vulkan ランタイム (vulkan-1.dll) が必要です: グラフィックドライバーを更新するか、プレーヤーを再インストールしてください。",
        "player_probe_crashed": "libmpv が読み込み中にクラッシュしました: プレーヤーは無効のままです。ログを確認してください。",
        "player_restart_required": "プレーヤーの有効化を完了するには、アプリケーションを再起動してください。",
        "player_install_btn": "プレーヤーをインストール",
        "player_install_confirm": "ビデオプレーヤーのコンポーネント (約 {size} MB) をダウンロードしてインストールしますか？",
        "player_installing": "プレーヤーをインストール中...",
        "player_install_ok": "プレーヤーをインストールしました。",
        "player_install_failed": "プレーヤーのインストールに失敗しました: ログを確認してください。",
        "player_credits": "動画再生: mpv (libmpv), {license}",
        "player_license_system": "システムライブラリ",
        "live_err_busy_install": "インストールを実行中です: 完了するまでお待ちください。",
        "player_playlist_sources": "ソース",
        "player_playlist_results": "結果",
    },
    "ko": {
        "player_badge": "플레이어",
        "player_badge_ok": "플레이어 준비 완료 (mpv {version})",
        "player_unavailable_title": "내장 플레이어를 사용할 수 없습니다",
        "player_missing_pymod": "python-mpv 패키지가 설치되어 있지 않습니다.",
        "player_missing_libmpv_linux": "libmpv가 설치되어 있지 않습니다. 다음 명령으로 설치하세요: {cmd}",
        "player_missing_libmpv_win": "libmpv가 설치되어 있지 않습니다. setup_windows.bat (Repair)를 실행하거나 지금 설치하세요.",
        "player_libmpv_too_old": "설치된 libmpv ({version})가 너무 오래되었습니다: 0.34 이상이 필요합니다.",
        "player_libmpv_load_failed": "libmpv를 불러올 수 없습니다 ({detail}). 파일이 손상되었거나 백신 프로그램에 의해 차단되었을 수 있습니다.",
        "player_vulkan_missing": "libmpv에는 Vulkan 런타임 (vulkan-1.dll)이 필요합니다: 그래픽 드라이버를 업데이트하거나 플레이어를 다시 설치하세요.",
        "player_probe_crashed": "libmpv가 로드 중에 충돌했습니다: 플레이어가 비활성화된 상태로 유지됩니다. 로그를 확인하세요.",
        "player_restart_required": "플레이어 활성화를 완료하려면 애플리케이션을 다시 시작하세요.",
        "player_install_btn": "플레이어 설치",
        "player_install_confirm": "비디오 플레이어 구성 요소를 다운로드하여 설치할까요 (약 {size} MB)?",
        "player_installing": "플레이어 설치 중...",
        "player_install_ok": "플레이어가 설치되었습니다.",
        "player_install_failed": "플레이어 설치에 실패했습니다: 로그를 확인하세요.",
        "player_credits": "동영상 재생: mpv (libmpv), {license}",
        "player_license_system": "시스템 라이브러리",
        "live_err_busy_install": "설치가 진행 중입니다: 완료될 때까지 기다리세요.",
        "player_playlist_sources": "소스",
        "player_playlist_results": "결과",
    },
    "no": {
        "player_badge": "Spiller",
        "player_badge_ok": "Spilleren er klar (mpv {version})",
        "player_unavailable_title": "Den innebygde spilleren er ikke tilgjengelig",
        "player_missing_pymod": "Pakken python-mpv er ikke installert.",
        "player_missing_libmpv_linux": "libmpv er ikke installert. Installer den med: {cmd}",
        "player_missing_libmpv_win": "libmpv er ikke installert. Kjør setup_windows.bat (Repair), eller installer den nå.",
        "player_libmpv_too_old": "Den installerte libmpv ({version}) er for gammel: versjon 0.34 eller nyere kreves.",
        "player_libmpv_load_failed": "libmpv kunne ikke lastes inn ({detail}). Filen kan være skadet eller blokkert av antivirusprogrammet.",
        "player_vulkan_missing": "libmpv trenger Vulkan-kjøretiden (vulkan-1.dll): oppdater grafikkdriveren, eller installer spilleren på nytt.",
        "player_probe_crashed": "libmpv krasjet under innlasting: spilleren forblir deaktivert. Se loggen.",
        "player_restart_required": "Start programmet på nytt for å fullføre aktiveringen av spilleren.",
        "player_install_btn": "Installer spiller",
        "player_install_confirm": "Vil du laste ned og installere komponentene til videospilleren (ca. {size} MB)?",
        "player_installing": "Installerer spilleren...",
        "player_install_ok": "Spilleren er installert.",
        "player_install_failed": "Installasjonen av spilleren mislyktes: se loggen.",
        "player_credits": "Videoavspilling: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installasjon pågår: vent til den er ferdig.",
        "player_playlist_sources": "Kilder",
        "player_playlist_results": "Resultater",
    },
    "pl": {
        "player_badge": "Odtwarzacz",
        "player_badge_ok": "Odtwarzacz gotowy (mpv {version})",
        "player_unavailable_title": "Wbudowany odtwarzacz jest niedostępny",
        "player_missing_pymod": "Pakiet python-mpv nie jest zainstalowany.",
        "player_missing_libmpv_linux": "Biblioteka libmpv nie jest zainstalowana. Zainstaluj ją poleceniem: {cmd}",
        "player_missing_libmpv_win": "Biblioteka libmpv nie jest zainstalowana. Uruchom setup_windows.bat (Repair) lub zainstaluj ją teraz.",
        "player_libmpv_too_old": "Zainstalowana biblioteka libmpv ({version}) jest zbyt stara: wymagana jest wersja 0.34 lub nowsza.",
        "player_libmpv_load_failed": "Nie można załadować biblioteki libmpv ({detail}). Plik może być uszkodzony lub zablokowany przez program antywirusowy.",
        "player_vulkan_missing": "Biblioteka libmpv wymaga środowiska uruchomieniowego Vulkan (vulkan-1.dll): zaktualizuj sterownik karty graficznej lub zainstaluj odtwarzacz ponownie.",
        "player_probe_crashed": "Biblioteka libmpv uległa awarii podczas ładowania: odtwarzacz pozostaje wyłączony. Sprawdź dziennik.",
        "player_restart_required": "Uruchom ponownie aplikację, aby dokończyć włączanie odtwarzacza.",
        "player_install_btn": "Zainstaluj odtwarzacz",
        "player_install_confirm": "Pobrać i zainstalować składniki odtwarzacza wideo (około {size} MB)?",
        "player_installing": "Instalowanie odtwarzacza...",
        "player_install_ok": "Odtwarzacz zainstalowany.",
        "player_install_failed": "Instalacja odtwarzacza nie powiodła się: sprawdź dziennik.",
        "player_credits": "Odtwarzanie wideo: mpv (libmpv), {license}",
        "player_license_system": "biblioteka systemowa",
        "live_err_busy_install": "Trwa instalacja: poczekaj, aż się zakończy.",
        "player_playlist_sources": "Źródła",
        "player_playlist_results": "Wyniki",
    },
    "pt": {
        "player_badge": "Player",
        "player_badge_ok": "Player pronto (mpv {version})",
        "player_unavailable_title": "Player integrado indisponível",
        "player_missing_pymod": "O pacote python-mpv não está instalado.",
        "player_missing_libmpv_linux": "A libmpv não está instalada. Instale-a com: {cmd}",
        "player_missing_libmpv_win": "A libmpv não está instalada. Execute setup_windows.bat (Repair) ou instale-a agora.",
        "player_libmpv_too_old": "A libmpv instalada ({version}) é antiga demais: é necessária a versão 0.34 ou mais recente.",
        "player_libmpv_load_failed": "Não foi possível carregar a libmpv ({detail}). O arquivo pode estar danificado ou bloqueado pelo antivírus.",
        "player_vulkan_missing": "A libmpv precisa do runtime Vulkan (vulkan-1.dll): atualize o driver gráfico ou instale o player novamente.",
        "player_probe_crashed": "A libmpv travou durante o carregamento: o player continua desativado. Veja o registro.",
        "player_restart_required": "Reinicie o aplicativo para concluir a ativação do player.",
        "player_install_btn": "Instalar player",
        "player_install_confirm": "Baixar e instalar os componentes do player de vídeo (cerca de {size} MB)?",
        "player_installing": "Instalando o player...",
        "player_install_ok": "Player instalado.",
        "player_install_failed": "A instalação do player falhou: veja o registro.",
        "player_credits": "Reprodução de vídeo: mpv (libmpv), {license}",
        "player_license_system": "biblioteca do sistema",
        "live_err_busy_install": "Há uma instalação em andamento: aguarde a conclusão.",
        "player_playlist_sources": "Fontes",
        "player_playlist_results": "Resultados",
    },
    "ro": {
        "player_badge": "Player",
        "player_badge_ok": "Playerul este pregătit (mpv {version})",
        "player_unavailable_title": "Playerul integrat nu este disponibil",
        "player_missing_pymod": "Pachetul python-mpv nu este instalat.",
        "player_missing_libmpv_linux": "libmpv nu este instalată. Instalați-o cu: {cmd}",
        "player_missing_libmpv_win": "libmpv nu este instalată. Rulați setup_windows.bat (Repair) sau instalați-o acum.",
        "player_libmpv_too_old": "libmpv instalată ({version}) este prea veche: este necesară versiunea 0.34 sau mai nouă.",
        "player_libmpv_load_failed": "libmpv nu a putut fi încărcată ({detail}). Fișierul poate fi deteriorat sau blocat de antivirus.",
        "player_vulkan_missing": "libmpv are nevoie de mediul de rulare Vulkan (vulkan-1.dll): actualizați driverul plăcii grafice sau reinstalați playerul.",
        "player_probe_crashed": "libmpv s-a oprit neașteptat în timpul încărcării: playerul rămâne dezactivat. Consultați jurnalul.",
        "player_restart_required": "Reporniți aplicația pentru a finaliza activarea playerului.",
        "player_install_btn": "Instalează playerul",
        "player_install_confirm": "Descărcați și instalați componentele playerului video (aproximativ {size} MB)?",
        "player_installing": "Se instalează playerul...",
        "player_install_ok": "Playerul a fost instalat.",
        "player_install_failed": "Instalarea playerului a eșuat: consultați jurnalul.",
        "player_credits": "Redare video: mpv (libmpv), {license}",
        "player_license_system": "bibliotecă de sistem",
        "live_err_busy_install": "O instalare este în curs: așteptați să se termine.",
        "player_playlist_sources": "Surse",
        "player_playlist_results": "Rezultate",
    },
    "ru": {
        "player_badge": "Плеер",
        "player_badge_ok": "Плеер готов (mpv {version})",
        "player_unavailable_title": "Встроенный плеер недоступен",
        "player_missing_pymod": "Пакет python-mpv не установлен.",
        "player_missing_libmpv_linux": "libmpv не установлена. Установите её командой: {cmd}",
        "player_missing_libmpv_win": "libmpv не установлена. Запустите setup_windows.bat (Repair) или установите её сейчас.",
        "player_libmpv_too_old": "Установленная libmpv ({version}) слишком старая: нужна версия 0.34 или новее.",
        "player_libmpv_load_failed": "Не удалось загрузить libmpv ({detail}). Возможно, файл повреждён или заблокирован антивирусом.",
        "player_vulkan_missing": "Для libmpv нужна среда выполнения Vulkan (vulkan-1.dll): обновите драйвер видеокарты или установите плеер заново.",
        "player_probe_crashed": "libmpv аварийно завершилась при загрузке: плеер остаётся отключённым. См. журнал.",
        "player_restart_required": "Перезапустите приложение, чтобы завершить включение плеера.",
        "player_install_btn": "Установить плеер",
        "player_install_confirm": "Скачать и установить компоненты видеоплеера (около {size} МБ)?",
        "player_installing": "Установка плеера...",
        "player_install_ok": "Плеер установлен.",
        "player_install_failed": "Не удалось установить плеер: см. журнал.",
        "player_credits": "Воспроизведение видео: mpv (libmpv), {license}",
        "player_license_system": "системная библиотека",
        "live_err_busy_install": "Идёт установка: дождитесь её завершения.",
        "player_playlist_sources": "Исходные файлы",
        "player_playlist_results": "Результаты",
    },
    "es": {
        "player_badge": "Reproductor",
        "player_badge_ok": "Reproductor listo (mpv {version})",
        "player_unavailable_title": "Reproductor integrado no disponible",
        "player_missing_pymod": "El paquete python-mpv no está instalado.",
        "player_missing_libmpv_linux": "libmpv no está instalada. Instálala con: {cmd}",
        "player_missing_libmpv_win": "libmpv no está instalada. Ejecuta setup_windows.bat (Repair) o instálala ahora.",
        "player_libmpv_too_old": "La libmpv instalada ({version}) es demasiado antigua: se necesita la versión 0.34 o posterior.",
        "player_libmpv_load_failed": "No se pudo cargar libmpv ({detail}). Puede que el archivo esté dañado o bloqueado por el antivirus.",
        "player_vulkan_missing": "libmpv necesita el runtime de Vulkan (vulkan-1.dll): actualiza el controlador gráfico o vuelve a instalar el reproductor.",
        "player_probe_crashed": "libmpv se bloqueó durante la carga: el reproductor sigue desactivado. Consulta el registro.",
        "player_restart_required": "Reinicia la aplicación para terminar de activar el reproductor.",
        "player_install_btn": "Instalar reproductor",
        "player_install_confirm": "¿Descargar e instalar los componentes del reproductor de vídeo (unos {size} MB)?",
        "player_installing": "Instalando el reproductor...",
        "player_install_ok": "Reproductor instalado.",
        "player_install_failed": "La instalación del reproductor falló: consulta el registro.",
        "player_credits": "Reproducción de vídeo: mpv (libmpv), {license}",
        "player_license_system": "biblioteca del sistema",
        "live_err_busy_install": "Hay una instalación en curso: espera a que termine.",
        "player_playlist_sources": "Fuentes",
        "player_playlist_results": "Resultados",
    },
    "sv": {
        "player_badge": "Spelare",
        "player_badge_ok": "Spelaren är redo (mpv {version})",
        "player_unavailable_title": "Den inbyggda spelaren är inte tillgänglig",
        "player_missing_pymod": "Paketet python-mpv är inte installerat.",
        "player_missing_libmpv_linux": "libmpv är inte installerat. Installera det med: {cmd}",
        "player_missing_libmpv_win": "libmpv är inte installerat. Kör setup_windows.bat (Repair) eller installera det nu.",
        "player_libmpv_too_old": "Den installerade libmpv ({version}) är för gammal: version 0.34 eller senare krävs.",
        "player_libmpv_load_failed": "libmpv kunde inte läsas in ({detail}). Filen kan vara skadad eller blockerad av antivirusprogrammet.",
        "player_vulkan_missing": "libmpv behöver Vulkan-körmiljön (vulkan-1.dll): uppdatera grafikdrivrutinen eller installera om spelaren.",
        "player_probe_crashed": "libmpv kraschade vid inläsningen: spelaren förblir inaktiverad. Se loggen.",
        "player_restart_required": "Starta om programmet för att slutföra aktiveringen av spelaren.",
        "player_install_btn": "Installera spelare",
        "player_install_confirm": "Vill du hämta och installera videospelarens komponenter (cirka {size} MB)?",
        "player_installing": "Installerar spelaren...",
        "player_install_ok": "Spelaren är installerad.",
        "player_install_failed": "Installationen av spelaren misslyckades: se loggen.",
        "player_credits": "Videouppspelning: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installation pågår: vänta tills den är klar.",
        "player_playlist_sources": "Källor",
        "player_playlist_results": "Resultat",
    },
    "tr": {
        "player_badge": "Oynatıcı",
        "player_badge_ok": "Oynatıcı hazır (mpv {version})",
        "player_unavailable_title": "Yerleşik oynatıcı kullanılamıyor",
        "player_missing_pymod": "python-mpv paketi yüklü değil.",
        "player_missing_libmpv_linux": "libmpv yüklü değil. Şu komutla yükleyin: {cmd}",
        "player_missing_libmpv_win": "libmpv yüklü değil. setup_windows.bat (Repair) çalıştırın veya şimdi yükleyin.",
        "player_libmpv_too_old": "Yüklü libmpv ({version}) çok eski: 0.34 veya daha yeni bir sürüm gerekiyor.",
        "player_libmpv_load_failed": "libmpv yüklenemedi ({detail}). Dosya bozuk olabilir veya virüsten koruma yazılımı tarafından engellenmiş olabilir.",
        "player_vulkan_missing": "libmpv, Vulkan çalışma zamanına (vulkan-1.dll) ihtiyaç duyuyor: grafik sürücüsünü güncelleyin veya oynatıcıyı yeniden yükleyin.",
        "player_probe_crashed": "libmpv yüklenirken çöktü: oynatıcı devre dışı kalıyor. Günlüğe bakın.",
        "player_restart_required": "Oynatıcının etkinleştirilmesini tamamlamak için uygulamayı yeniden başlatın.",
        "player_install_btn": "Oynatıcıyı yükle",
        "player_install_confirm": "Video oynatıcı bileşenleri indirilip yüklensin mi (yaklaşık {size} MB)?",
        "player_installing": "Oynatıcı yükleniyor...",
        "player_install_ok": "Oynatıcı yüklendi.",
        "player_install_failed": "Oynatıcı yüklenemedi: günlüğe bakın.",
        "player_credits": "Video oynatma: mpv (libmpv), {license}",
        "player_license_system": "sistem kitaplığı",
        "live_err_busy_install": "Bir yükleme devam ediyor: bitmesini bekleyin.",
        "player_playlist_sources": "Kaynaklar",
        "player_playlist_results": "Sonuçlar",
    },
    "uk": {
        "player_badge": "Плеєр",
        "player_badge_ok": "Плеєр готовий (mpv {version})",
        "player_unavailable_title": "Вбудований плеєр недоступний",
        "player_missing_pymod": "Пакет python-mpv не встановлено.",
        "player_missing_libmpv_linux": "libmpv не встановлено. Встановіть її командою: {cmd}",
        "player_missing_libmpv_win": "libmpv не встановлено. Запустіть setup_windows.bat (Repair) або встановіть її зараз.",
        "player_libmpv_too_old": "Встановлена libmpv ({version}) занадто стара: потрібна версія 0.34 або новіша.",
        "player_libmpv_load_failed": "Не вдалося завантажити libmpv ({detail}). Можливо, файл пошкоджено або заблоковано антивірусом.",
        "player_vulkan_missing": "Для libmpv потрібне середовище виконання Vulkan (vulkan-1.dll): оновіть драйвер відеокарти або встановіть плеєр знову.",
        "player_probe_crashed": "libmpv аварійно завершила роботу під час завантаження: плеєр залишається вимкненим. Див. журнал.",
        "player_restart_required": "Перезапустіть застосунок, щоб завершити увімкнення плеєра.",
        "player_install_btn": "Встановити плеєр",
        "player_install_confirm": "Завантажити та встановити компоненти відеоплеєра (близько {size} МБ)?",
        "player_installing": "Встановлення плеєра...",
        "player_install_ok": "Плеєр встановлено.",
        "player_install_failed": "Не вдалося встановити плеєр: див. журнал.",
        "player_credits": "Відтворення відео: mpv (libmpv), {license}",
        "player_license_system": "системна бібліотека",
        "live_err_busy_install": "Триває встановлення: зачекайте, доки воно завершиться.",
        "player_playlist_sources": "Джерела",
        "player_playlist_results": "Результати",
    },
    "vi": {
        "player_badge": "Trình phát",
        "player_badge_ok": "Trình phát đã sẵn sàng (mpv {version})",
        "player_unavailable_title": "Trình phát tích hợp không khả dụng",
        "player_missing_pymod": "Gói python-mpv chưa được cài đặt.",
        "player_missing_libmpv_linux": "libmpv chưa được cài đặt. Hãy cài đặt bằng lệnh: {cmd}",
        "player_missing_libmpv_win": "libmpv chưa được cài đặt. Hãy chạy setup_windows.bat (Repair) hoặc cài đặt ngay.",
        "player_libmpv_too_old": "libmpv đã cài đặt ({version}) quá cũ: cần phiên bản 0.34 trở lên.",
        "player_libmpv_load_failed": "Không thể tải libmpv ({detail}). Tệp có thể bị hỏng hoặc bị phần mềm diệt virus chặn.",
        "player_vulkan_missing": "libmpv cần môi trường chạy Vulkan (vulkan-1.dll): hãy cập nhật trình điều khiển đồ họa hoặc cài đặt lại trình phát.",
        "player_probe_crashed": "libmpv bị lỗi khi tải: trình phát vẫn bị tắt. Xem nhật ký.",
        "player_restart_required": "Hãy khởi động lại ứng dụng để hoàn tất việc bật trình phát.",
        "player_install_btn": "Cài đặt trình phát",
        "player_install_confirm": "Tải xuống và cài đặt các thành phần của trình phát video (khoảng {size} MB)?",
        "player_installing": "Đang cài đặt trình phát...",
        "player_install_ok": "Đã cài đặt trình phát.",
        "player_install_failed": "Cài đặt trình phát thất bại: xem nhật ký.",
        "player_credits": "Phát video: mpv (libmpv), {license}",
        "player_license_system": "thư viện hệ thống",
        "live_err_busy_install": "Đang có một quá trình cài đặt: hãy chờ đến khi hoàn tất.",
        "player_playlist_sources": "Nguồn",
        "player_playlist_results": "Kết quả",
    },
}

PLAYER_KEYS: tuple[str, ...] = tuple(sorted(PLAYER_UI_STRINGS["en"]))


def merge_into(ui_strings: dict[str, dict[str, str]]) -> list[str]:
    """Add the player strings to ``ui_strings`` in place and return the problems found.

    Never raises (spec 2.6, [CC] G27): a key that already exists with a
    different value keeps the existing value and is reported as
    ``"collision <lang>.<key>"``; a language the target does not have is
    skipped and reported as ``"unknown language '<lang>'"``. Merging twice is
    harmless (equal values are not collisions).
    """
    problems: list[str] = []
    for lang, entries in PLAYER_UI_STRINGS.items():
        bucket = ui_strings.get(lang)
        if bucket is None:
            problems.append(f"unknown language {lang!r}")
            continue
        for key, value in entries.items():
            existing = bucket.get(key)
            if existing is not None and existing != value:
                problems.append(f"collision {lang}.{key}")
                continue
            bucket[key] = value
    return problems
