"""Log panel messages in all 26 UI languages.

The app writes its own events (clicks, choices, results, errors) to the Log
panel and the log file in the interface language. Merged into UI_STRINGS at
startup with :func:`merge_into`, like the other string modules; the i18n
tests check keys and placeholders in every language.
"""

from __future__ import annotations

_KEYS = (
    "log_started", "log_file", "log_click", "log_click_disabled", "log_on", "log_off",
    "log_choice", "log_error", "log_window", "log_settings", "log_player", "log_live",
    "log_vp", "log_state_loading", "log_state_playing", "log_state_idle",
    "log_live_start", "log_live_end",
    "log_level_info", "log_level_warn", "log_level_error", "log_session_live",
)

_T: dict[str, tuple[str, ...]] = {
    "en": ("Video Translator AI {version} started: Python {py}, {os}",
           "Log file (the last {days} days are kept): {path}",
           "Click: {name}", "Click on a disabled control: {name}", "{name}: on", "{name}: off",
           "{name}: {value}", "Unexpected error in {where}: {error}", "Window opened: {title}",
           "Appearance: theme {theme}, accent {accent}, text size {scale}",
           "Player: {command}", "Real-time bar: {command} {value}",
           "Voice preview {voice}: {state}", "preparing", "playing", "finished",
           'Real-time translation started: {mode}, translation {engine}, speech recognition {asr}. {voice}',
           'Real-time translation ended: voice lines spoken {spoken}, lost {lost}.',
           'INFO', 'WARNING', 'ERROR',
           'Real-time settings: {mode}, translation {engine}, speech recognition {asr}. {voice}'),
    "it": ("Video Translator AI {version} avviato: Python {py}, {os}",
           "File di log (si tengono gli ultimi {days} giorni): {path}",
           "Clic: {name}", "Clic su un comando disattivato: {name}", "{name}: attivo",
           "{name}: disattivo", "{name}: {value}", "Errore imprevisto in {where}: {error}",
           "Finestra aperta: {title}",
           "Aspetto: tema {theme}, accento {accent}, dimensione testo {scale}",
           "Player: {command}", "Barra tempo reale: {command} {value}",
           "Ascolto voce {voice}: {state}", "in preparazione", "in riproduzione", "finito",
           'Traduzione in tempo reale avviata: {mode}, traduzione {engine}, riconoscimento vocale {asr}. {voice}',
           'Traduzione in tempo reale terminata: frasi dette {spoken}, perse {lost}.',
           'INFO', 'AVVISO', 'ERRORE',
           'Impostazioni tempo reale: {mode}, traduzione {engine}, riconoscimento vocale {asr}. {voice}'),
    "ar": ("بدأ Video Translator AI {version}: Python {py}، {os}",
           "ملف السجل (يُحتفظ بآخر {days} أيام): {path}",
           "نقر: {name}", "نقر على عنصر معطّل: {name}", "{name}: مفعّل", "{name}: معطّل",
           "{name}: {value}", "خطأ غير متوقع في {where}: {error}", "نافذة مفتوحة: {title}",
           "المظهر: السمة {theme}، اللون {accent}، حجم النص {scale}",
           "المشغّل: {command}", "شريط الوقت الفعلي: {command} {value}",
           "معاينة الصوت {voice}: {state}", "قيد التحضير", "قيد التشغيل", "انتهى",
           'بدأت الترجمة الفورية: {mode}، الترجمة {engine}، التعرّف على الكلام {asr}. {voice}',
           'انتهت الترجمة الفورية: جمل منطوقة {spoken}، مفقودة {lost}.',
           'معلومة', 'تحذير', 'خطأ',
           'إعدادات الوقت الفعلي: {mode}، الترجمة {engine}، التعرّف على الكلام {asr}. {voice}'),
    "zh": ("Video Translator AI {version} 已启动：Python {py}，{os}",
           "日志文件（保留最近 {days} 天）：{path}",
           "点击：{name}", "点击了已禁用的控件：{name}", "{name}：开", "{name}：关",
           "{name}：{value}", "{where} 中出现意外错误：{error}", "已打开窗口：{title}",
           "外观：主题 {theme}，强调色 {accent}，文字大小 {scale}",
           "播放器：{command}", "实时栏：{command} {value}",
           "试听语音 {voice}：{state}", "准备中", "播放中", "已结束",
           '实时翻译已开始：{mode}，翻译 {engine}，语音识别 {asr}。{voice}',
           '实时翻译已结束：已说出 {spoken} 句，丢失 {lost} 句。',
           '信息', '警告', '错误',
           '实时设置：{mode}，翻译 {engine}，语音识别 {asr}。{voice}'),
    "cs": ("Video Translator AI {version} spuštěn: Python {py}, {os}",
           "Soubor protokolu (uchovává se posledních {days} dní): {path}",
           "Klik: {name}", "Klik na neaktivní ovládací prvek: {name}", "{name}: zapnuto",
           "{name}: vypnuto", "{name}: {value}", "Neočekávaná chyba v {where}: {error}",
           "Otevřené okno: {title}",
           "Vzhled: motiv {theme}, zvýraznění {accent}, velikost textu {scale}",
           "Přehrávač: {command}", "Lišta v reálném čase: {command} {value}",
           "Poslech hlasu {voice}: {state}", "připravuje se", "přehrává se", "dokončeno",
           'Překlad v reálném čase spuštěn: {mode}, překlad {engine}, rozpoznávání řeči {asr}. {voice}',
           'Překlad v reálném čase ukončen: vyslovené věty {spoken}, ztracené {lost}.',
           'INFO', 'VAROVÁNÍ', 'CHYBA',
           'Nastavení reálného času: {mode}, překlad {engine}, rozpoznávání řeči {asr}. {voice}'),
    "da": ("Video Translator AI {version} startet: Python {py}, {os}",
           "Logfil (de seneste {days} dage gemmes): {path}",
           "Klik: {name}", "Klik på et deaktiveret element: {name}", "{name}: til",
           "{name}: fra", "{name}: {value}", "Uventet fejl i {where}: {error}",
           "Vindue åbnet: {title}",
           "Udseende: tema {theme}, accent {accent}, tekststørrelse {scale}",
           "Afspiller: {command}", "Realtidsbjælke: {command} {value}",
           "Stemmeprøve {voice}: {state}", "forberedes", "afspilles", "færdig",
           'Realtidsoversættelse startet: {mode}, oversættelse {engine}, talegenkendelse {asr}. {voice}',
           'Realtidsoversættelse afsluttet: sætninger sagt {spoken}, tabt {lost}.',
           'INFO', 'ADVARSEL', 'FEJL',
           'Realtidsindstillinger: {mode}, oversættelse {engine}, talegenkendelse {asr}. {voice}'),
    "nl": ("Video Translator AI {version} gestart: Python {py}, {os}",
           "Logbestand (de laatste {days} dagen worden bewaard): {path}",
           "Klik: {name}", "Klik op een uitgeschakeld element: {name}", "{name}: aan",
           "{name}: uit", "{name}: {value}", "Onverwachte fout in {where}: {error}",
           "Venster geopend: {title}",
           "Weergave: thema {theme}, accent {accent}, tekstgrootte {scale}",
           "Speler: {command}", "Realtimebalk: {command} {value}",
           "Stemvoorbeeld {voice}: {state}", "wordt voorbereid", "speelt af", "klaar",
           'Realtime vertaling gestart: {mode}, vertaling {engine}, spraakherkenning {asr}. {voice}',
           'Realtime vertaling beëindigd: zinnen uitgesproken {spoken}, verloren {lost}.',
           'INFO', 'WAARSCHUWING', 'FOUT',
           'Realtime-instellingen: {mode}, vertaling {engine}, spraakherkenning {asr}. {voice}'),
    "fi": ("Video Translator AI {version} käynnistyi: Python {py}, {os}",
           "Lokitiedosto (viimeiset {days} päivää säilytetään): {path}",
           "Napsautus: {name}", "Napsautus pois käytöstä olevaan ohjaimeen: {name}",
           "{name}: päällä", "{name}: pois", "{name}: {value}",
           "Odottamaton virhe kohteessa {where}: {error}", "Ikkuna avattu: {title}",
           "Ulkoasu: teema {theme}, korostus {accent}, tekstin koko {scale}",
           "Soitin: {command}", "Reaaliaikapalkki: {command} {value}",
           "Äänen kuuntelu {voice}: {state}", "valmistellaan", "toistetaan", "valmis",
           'Reaaliaikainen käännös käynnistyi: {mode}, käännös {engine}, puheentunnistus {asr}. {voice}',
           'Reaaliaikainen käännös päättyi: lausuttuja lauseita {spoken}, menetettyjä {lost}.',
           'INFO', 'VAROITUS', 'VIRHE',
           'Reaaliaika-asetukset: {mode}, käännös {engine}, puheentunnistus {asr}. {voice}'),
    "fr": ("Video Translator AI {version} démarré : Python {py}, {os}",
           "Fichier journal (les {days} derniers jours sont conservés) : {path}",
           "Clic : {name}", "Clic sur une commande désactivée : {name}", "{name} : activé",
           "{name} : désactivé", "{name} : {value}", "Erreur inattendue dans {where} : {error}",
           "Fenêtre ouverte : {title}",
           "Apparence : thème {theme}, accent {accent}, taille du texte {scale}",
           "Lecteur : {command}", "Barre temps réel : {command} {value}",
           "Écoute de la voix {voice} : {state}", "en préparation", "en lecture", "terminée",
           'Traduction en temps réel démarrée : {mode}, traduction {engine}, reconnaissance vocale {asr}. {voice}',
           'Traduction en temps réel terminée : phrases dites {spoken}, perdues {lost}.',
           'INFO', 'AVERTISSEMENT', 'ERREUR',
           'Réglages temps réel : {mode}, traduction {engine}, reconnaissance vocale {asr}. {voice}'),
    "de": ("Video Translator AI {version} gestartet: Python {py}, {os}",
           "Protokolldatei (die letzten {days} Tage werden behalten): {path}",
           "Klick: {name}", "Klick auf ein deaktiviertes Element: {name}", "{name}: an",
           "{name}: aus", "{name}: {value}", "Unerwarteter Fehler in {where}: {error}",
           "Fenster geöffnet: {title}",
           "Darstellung: Design {theme}, Akzent {accent}, Textgröße {scale}",
           "Player: {command}", "Echtzeitleiste: {command} {value}",
           "Stimmprobe {voice}: {state}", "wird vorbereitet", "wird abgespielt", "beendet",
           'Echtzeitübersetzung gestartet: {mode}, Übersetzung {engine}, Spracherkennung {asr}. {voice}',
           'Echtzeitübersetzung beendet: gesprochene Sätze {spoken}, verlorene {lost}.',
           'INFO', 'WARNUNG', 'FEHLER',
           'Echtzeit-Einstellungen: {mode}, Übersetzung {engine}, Spracherkennung {asr}. {voice}'),
    "el": ("Το Video Translator AI {version} ξεκίνησε: Python {py}, {os}",
           "Αρχείο καταγραφής (κρατούνται οι τελευταίες {days} ημέρες): {path}",
           "Κλικ: {name}", "Κλικ σε ανενεργό στοιχείο: {name}", "{name}: ενεργό",
           "{name}: ανενεργό", "{name}: {value}", "Απρόσμενο σφάλμα στο {where}: {error}",
           "Άνοιξε παράθυρο: {title}",
           "Εμφάνιση: θέμα {theme}, χρώμα έμφασης {accent}, μέγεθος κειμένου {scale}",
           "Πρόγραμμα αναπαραγωγής: {command}", "Γραμμή πραγματικού χρόνου: {command} {value}",
           "Ακρόαση φωνής {voice}: {state}", "προετοιμάζεται", "αναπαράγεται", "ολοκληρώθηκε",
           'Η μετάφραση σε πραγματικό χρόνο ξεκίνησε: {mode}, μετάφραση {engine}, αναγνώριση ομιλίας {asr}. {voice}',
           'Η μετάφραση σε πραγματικό χρόνο τελείωσε: φράσεις που ειπώθηκαν {spoken}, χαμένες {lost}.',
           'ΠΛΗΡΟΦ.', 'ΠΡΟΕΙΔ.', 'ΣΦΑΛΜΑ',
           'Ρυθμίσεις πραγματικού χρόνου: {mode}, μετάφραση {engine}, αναγνώριση ομιλίας {asr}. {voice}'),
    "hi": ("Video Translator AI {version} शुरू हुआ: Python {py}, {os}",
           "लॉग फ़ाइल (पिछले {days} दिन रखे जाते हैं): {path}",
           "क्लिक: {name}", "निष्क्रिय नियंत्रण पर क्लिक: {name}", "{name}: चालू",
           "{name}: बंद", "{name}: {value}", "{where} में अनपेक्षित त्रुटि: {error}",
           "विंडो खुली: {title}",
           "रूप: थीम {theme}, एक्सेंट {accent}, टेक्स्ट आकार {scale}",
           "प्लेयर: {command}", "रीयल-टाइम बार: {command} {value}",
           "आवाज़ पूर्वावलोकन {voice}: {state}", "तैयार हो रहा है", "चल रहा है", "समाप्त",
           'रीयल-टाइम अनुवाद शुरू: {mode}, अनुवाद {engine}, वाक् पहचान {asr}। {voice}',
           'रीयल-टाइम अनुवाद समाप्त: बोले गए वाक्य {spoken}, छूटे {lost}।',
           'सूचना', 'चेतावनी', 'त्रुटि',
           'रीयल-टाइम सेटिंग्स: {mode}, अनुवाद {engine}, वाक् पहचान {asr}। {voice}'),
    "hu": ("A Video Translator AI {version} elindult: Python {py}, {os}",
           "Naplófájl (az utolsó {days} nap marad meg): {path}",
           "Kattintás: {name}", "Kattintás letiltott vezérlőre: {name}", "{name}: be",
           "{name}: ki", "{name}: {value}", "Váratlan hiba itt: {where}: {error}",
           "Megnyitott ablak: {title}",
           "Megjelenés: téma {theme}, kiemelés {accent}, szövegméret {scale}",
           "Lejátszó: {command}", "Valós idejű sáv: {command} {value}",
           "Hangminta {voice}: {state}", "előkészítés", "lejátszás", "befejezve",
           'A valós idejű fordítás elindult: {mode}, fordítás {engine}, beszédfelismerés {asr}. {voice}',
           'A valós idejű fordítás véget ért: elhangzott mondatok {spoken}, elveszett {lost}.',
           'INFÓ', 'FIGYELEM', 'HIBA',
           'Valós idejű beállítások: {mode}, fordítás {engine}, beszédfelismerés {asr}. {voice}'),
    "id": ("Video Translator AI {version} dimulai: Python {py}, {os}",
           "Berkas log ({days} hari terakhir disimpan): {path}",
           "Klik: {name}", "Klik pada kontrol nonaktif: {name}", "{name}: aktif",
           "{name}: nonaktif", "{name}: {value}", "Kesalahan tak terduga di {where}: {error}",
           "Jendela dibuka: {title}",
           "Tampilan: tema {theme}, aksen {accent}, ukuran teks {scale}",
           "Pemutar: {command}", "Bilah waktu nyata: {command} {value}",
           "Pratinjau suara {voice}: {state}", "sedang disiapkan", "sedang diputar", "selesai",
           'Terjemahan waktu nyata dimulai: {mode}, terjemahan {engine}, pengenalan suara {asr}. {voice}',
           'Terjemahan waktu nyata selesai: kalimat diucapkan {spoken}, hilang {lost}.',
           'INFO', 'PERINGATAN', 'GALAT',
           'Pengaturan waktu nyata: {mode}, terjemahan {engine}, pengenalan suara {asr}. {voice}'),
    "ja": ("Video Translator AI {version} を起動しました：Python {py}、{os}",
           "ログファイル（直近 {days} 日分を保存）：{path}",
           "クリック：{name}", "無効なコントロールをクリック：{name}", "{name}：オン",
           "{name}：オフ", "{name}：{value}", "{where} で予期しないエラー：{error}",
           "ウィンドウを開きました：{title}",
           "外観：テーマ {theme}、アクセント {accent}、文字サイズ {scale}",
           "プレーヤー：{command}", "リアルタイムバー：{command} {value}",
           "音声の試聴 {voice}：{state}", "準備中", "再生中", "終了",
           'リアルタイム翻訳を開始：{mode}、翻訳 {engine}、音声認識 {asr}。{voice}',
           'リアルタイム翻訳を終了：話した文 {spoken}、失われた文 {lost}。',
           '情報', '警告', 'エラー',
           'リアルタイム設定：{mode}、翻訳 {engine}、音声認識 {asr}。{voice}'),
    "ko": ("Video Translator AI {version} 시작: Python {py}, {os}",
           "로그 파일(최근 {days}일 보관): {path}",
           "클릭: {name}", "비활성 컨트롤 클릭: {name}", "{name}: 켬", "{name}: 끔",
           "{name}: {value}", "{where}에서 예기치 않은 오류: {error}", "창 열림: {title}",
           "모양: 테마 {theme}, 강조색 {accent}, 글자 크기 {scale}",
           "플레이어: {command}", "실시간 막대: {command} {value}",
           "음성 미리 듣기 {voice}: {state}", "준비 중", "재생 중", "완료",
           '실시간 번역 시작: {mode}, 번역 {engine}, 음성 인식 {asr}. {voice}',
           '실시간 번역 종료: 말한 문장 {spoken}, 놓친 문장 {lost}.',
           '정보', '경고', '오류',
           '실시간 설정: {mode}, 번역 {engine}, 음성 인식 {asr}. {voice}'),
    "no": ("Video Translator AI {version} startet: Python {py}, {os}",
           "Loggfil (de siste {days} dagene beholdes): {path}",
           "Klikk: {name}", "Klikk på en deaktivert kontroll: {name}", "{name}: på",
           "{name}: av", "{name}: {value}", "Uventet feil i {where}: {error}",
           "Vindu åpnet: {title}",
           "Utseende: tema {theme}, aksent {accent}, tekststørrelse {scale}",
           "Spiller: {command}", "Sanntidslinje: {command} {value}",
           "Stemmeprøve {voice}: {state}", "forberedes", "spilles av", "ferdig",
           'Sanntidsoversettelse startet: {mode}, oversettelse {engine}, talegjenkjenning {asr}. {voice}',
           'Sanntidsoversettelse avsluttet: setninger sagt {spoken}, tapt {lost}.',
           'INFO', 'ADVARSEL', 'FEIL',
           'Sanntidsinnstillinger: {mode}, oversettelse {engine}, talegjenkjenning {asr}. {voice}'),
    "pl": ("Uruchomiono Video Translator AI {version}: Python {py}, {os}",
           "Plik dziennika (przechowywane są ostatnie {days} dni): {path}",
           "Kliknięcie: {name}", "Kliknięcie nieaktywnego elementu: {name}", "{name}: wł.",
           "{name}: wył.", "{name}: {value}", "Nieoczekiwany błąd w {where}: {error}",
           "Otwarto okno: {title}",
           "Wygląd: motyw {theme}, akcent {accent}, rozmiar tekstu {scale}",
           "Odtwarzacz: {command}", "Pasek czasu rzeczywistego: {command} {value}",
           "Odsłuch głosu {voice}: {state}", "przygotowanie", "odtwarzanie", "zakończono",
           'Tłumaczenie w czasie rzeczywistym rozpoczęte: {mode}, tłumaczenie {engine}, rozpoznawanie mowy {asr}. {voice}',
           'Tłumaczenie w czasie rzeczywistym zakończone: zdania wypowiedziane {spoken}, utracone {lost}.',
           'INFO', 'OSTRZEŻENIE', 'BŁĄD',
           'Ustawienia czasu rzeczywistego: {mode}, tłumaczenie {engine}, rozpoznawanie mowy {asr}. {voice}'),
    "pt": ("Video Translator AI {version} iniciado: Python {py}, {os}",
           "Ficheiro de registo (guardam-se os últimos {days} dias): {path}",
           "Clique: {name}", "Clique num controlo desativado: {name}", "{name}: ligado",
           "{name}: desligado", "{name}: {value}", "Erro inesperado em {where}: {error}",
           "Janela aberta: {title}",
           "Aspeto: tema {theme}, destaque {accent}, tamanho do texto {scale}",
           "Leitor: {command}", "Barra em tempo real: {command} {value}",
           "Pré-escuta da voz {voice}: {state}", "a preparar", "a reproduzir", "terminada",
           'Tradução em tempo real iniciada: {mode}, tradução {engine}, reconhecimento de voz {asr}. {voice}',
           'Tradução em tempo real terminada: frases ditas {spoken}, perdidas {lost}.',
           'INFO', 'AVISO', 'ERRO',
           'Definições de tempo real: {mode}, tradução {engine}, reconhecimento de voz {asr}. {voice}'),
    "ro": ("Video Translator AI {version} a pornit: Python {py}, {os}",
           "Fișier jurnal (se păstrează ultimele {days} zile): {path}",
           "Clic: {name}", "Clic pe o comandă dezactivată: {name}", "{name}: activat",
           "{name}: dezactivat", "{name}: {value}", "Eroare neașteptată în {where}: {error}",
           "Fereastră deschisă: {title}",
           "Aspect: temă {theme}, accent {accent}, dimensiune text {scale}",
           "Player: {command}", "Bara în timp real: {command} {value}",
           "Ascultare voce {voice}: {state}", "în pregătire", "în redare", "terminată",
           'Traducerea în timp real a pornit: {mode}, traducere {engine}, recunoaștere vocală {asr}. {voice}',
           'Traducerea în timp real s-a încheiat: propoziții rostite {spoken}, pierdute {lost}.',
           'INFO', 'AVERTISMENT', 'EROARE',
           'Setări timp real: {mode}, traducere {engine}, recunoaștere vocală {asr}. {voice}'),
    "ru": ("Video Translator AI {version} запущен: Python {py}, {os}",
           "Файл журнала (хранятся последние {days} дней): {path}",
           "Щелчок: {name}", "Щелчок по неактивному элементу: {name}", "{name}: вкл.",
           "{name}: выкл.", "{name}: {value}", "Непредвиденная ошибка в {where}: {error}",
           "Открыто окно: {title}",
           "Оформление: тема {theme}, акцент {accent}, размер текста {scale}",
           "Плеер: {command}", "Панель реального времени: {command} {value}",
           "Прослушивание голоса {voice}: {state}", "подготовка", "воспроизведение",
           "завершено",
           'Перевод в реальном времени запущен: {mode}, перевод {engine}, распознавание речи {asr}. {voice}',
           'Перевод в реальном времени завершён: произнесено фраз {spoken}, потеряно {lost}.',
           'ИНФО', 'ВНИМАНИЕ', 'ОШИБКА',
           'Настройки реального времени: {mode}, перевод {engine}, распознавание речи {asr}. {voice}'),
    "es": ("Video Translator AI {version} iniciado: Python {py}, {os}",
           "Archivo de registro (se conservan los últimos {days} días): {path}",
           "Clic: {name}", "Clic en un control desactivado: {name}", "{name}: activado",
           "{name}: desactivado", "{name}: {value}", "Error inesperado en {where}: {error}",
           "Ventana abierta: {title}",
           "Apariencia: tema {theme}, acento {accent}, tamaño del texto {scale}",
           "Reproductor: {command}", "Barra en tiempo real: {command} {value}",
           "Escucha de la voz {voice}: {state}", "preparando", "reproduciendo", "terminada",
           'Traducción en tiempo real iniciada: {mode}, traducción {engine}, reconocimiento de voz {asr}. {voice}',
           'Traducción en tiempo real terminada: frases dichas {spoken}, perdidas {lost}.',
           'INFO', 'AVISO', 'ERROR',
           'Ajustes de tiempo real: {mode}, traducción {engine}, reconocimiento de voz {asr}. {voice}'),
    "sv": ("Video Translator AI {version} startad: Python {py}, {os}",
           "Loggfil (de senaste {days} dagarna sparas): {path}",
           "Klick: {name}", "Klick på en inaktiverad kontroll: {name}", "{name}: på",
           "{name}: av", "{name}: {value}", "Oväntat fel i {where}: {error}",
           "Fönster öppnat: {title}",
           "Utseende: tema {theme}, accent {accent}, textstorlek {scale}",
           "Spelare: {command}", "Realtidsfält: {command} {value}",
           "Röstprov {voice}: {state}", "förbereds", "spelas upp", "klar",
           'Realtidsöversättning startad: {mode}, översättning {engine}, taligenkänning {asr}. {voice}',
           'Realtidsöversättning avslutad: meningar sagda {spoken}, förlorade {lost}.',
           'INFO', 'VARNING', 'FEL',
           'Realtidsinställningar: {mode}, översättning {engine}, taligenkänning {asr}. {voice}'),
    "tr": ("Video Translator AI {version} başlatıldı: Python {py}, {os}",
           "Günlük dosyası (son {days} gün saklanır): {path}",
           "Tıklama: {name}", "Devre dışı denetime tıklama: {name}", "{name}: açık",
           "{name}: kapalı", "{name}: {value}", "{where} içinde beklenmeyen hata: {error}",
           "Pencere açıldı: {title}",
           "Görünüm: tema {theme}, vurgu {accent}, metin boyutu {scale}",
           "Oynatıcı: {command}", "Gerçek zamanlı çubuk: {command} {value}",
           "Ses önizleme {voice}: {state}", "hazırlanıyor", "oynatılıyor", "bitti",
           'Gerçek zamanlı çeviri başladı: {mode}, çeviri {engine}, konuşma tanıma {asr}. {voice}',
           'Gerçek zamanlı çeviri bitti: söylenen cümle {spoken}, kaybolan {lost}.',
           'BİLGİ', 'UYARI', 'HATA',
           'Gerçek zamanlı ayarlar: {mode}, çeviri {engine}, konuşma tanıma {asr}. {voice}'),
    "uk": ("Video Translator AI {version} запущено: Python {py}, {os}",
           "Файл журналу (зберігаються останні {days} днів): {path}",
           "Клацання: {name}", "Клацання по неактивному елементу: {name}", "{name}: увімк.",
           "{name}: вимк.", "{name}: {value}", "Неочікувана помилка в {where}: {error}",
           "Відкрито вікно: {title}",
           "Вигляд: тема {theme}, акцент {accent}, розмір тексту {scale}",
           "Плеєр: {command}", "Панель реального часу: {command} {value}",
           "Прослуховування голосу {voice}: {state}", "підготовка", "відтворення",
           "завершено",
           'Переклад у реальному часі запущено: {mode}, переклад {engine}, розпізнавання мовлення {asr}. {voice}',
           'Переклад у реальному часі завершено: вимовлено фраз {spoken}, втрачено {lost}.',
           'ІНФО', 'УВАГА', 'ПОМИЛКА',
           'Налаштування реального часу: {mode}, переклад {engine}, розпізнавання мовлення {asr}. {voice}'),
    "vi": ("Video Translator AI {version} đã khởi động: Python {py}, {os}",
           "Tệp nhật ký (giữ {days} ngày gần nhất): {path}",
           "Nhấp: {name}", "Nhấp vào điều khiển bị tắt: {name}", "{name}: bật",
           "{name}: tắt", "{name}: {value}", "Lỗi không mong muốn trong {where}: {error}",
           "Đã mở cửa sổ: {title}",
           "Giao diện: chủ đề {theme}, màu nhấn {accent}, cỡ chữ {scale}",
           "Trình phát: {command}", "Thanh thời gian thực: {command} {value}",
           "Nghe thử giọng {voice}: {state}", "đang chuẩn bị", "đang phát", "đã xong",
           'Đã bắt đầu dịch thời gian thực: {mode}, dịch {engine}, nhận dạng giọng nói {asr}. {voice}',
           'Đã kết thúc dịch thời gian thực: câu đã nói {spoken}, bị mất {lost}.',
           'THÔNG TIN', 'CẢNH BÁO', 'LỖI',
           'Cài đặt thời gian thực: {mode}, dịch {engine}, nhận dạng giọng nói {asr}. {voice}'),
}

LOG_UI_STRINGS: dict[str, dict[str, str]] = {
    lang: dict(zip(_KEYS, values)) for lang, values in _T.items()
}


def merge_into(ui_strings: dict[str, dict[str, str]]) -> list[str]:
    """Add these strings to ``ui_strings`` in place; return the problems found."""
    problems: list[str] = []
    for lang, values in _T.items():
        if len(values) != len(_KEYS):
            problems.append(f"{lang}: {len(values)} strings for {len(_KEYS)} keys")
    for lang, entries in LOG_UI_STRINGS.items():
        bucket = ui_strings.get(lang)
        if bucket is None:
            problems.append(f"unknown language {lang!r}")
            continue
        for key, value in entries.items():
            existing = bucket.get(key)
            if existing is not None and existing != value:
                problems.append(f"collision {lang}.{key}")
                continue
            bucket[key] = value
    return problems
