"""Log panel messages in all 26 UI languages.

The app writes its own events (clicks, choices, results, errors) to the Log
panel and the log file in the interface language. Merged into UI_STRINGS at
startup with :func:`merge_into`, like the other string modules; the i18n
tests check keys and placeholders in every language.
"""

from __future__ import annotations

_KEYS = (
    "log_started", "log_file", "log_click", "log_click_disabled", "log_on", "log_off",
    "log_choice", "log_error", "log_window", "log_settings", "log_player", "log_live",
    "log_vp", "log_state_loading", "log_state_playing", "log_state_idle",
)

_T: dict[str, tuple[str, ...]] = {
    "en": ("Video Translator AI started: Python {py}, {os}",
           "Log file (the last {days} days are kept): {path}",
           "Click: {name}", "Click on a disabled control: {name}", "{name}: on", "{name}: off",
           "{name}: {value}", "Unexpected error in {where}: {error}", "Window opened: {title}",
           "Appearance: theme {theme}, accent {accent}, text size {scale}",
           "Player: {command}", "Real-time bar: {command} {value}",
           "Voice preview {voice}: {state}", "preparing", "playing", "finished"),
    "it": ("Video Translator AI avviato: Python {py}, {os}",
           "File di log (si tengono gli ultimi {days} giorni): {path}",
           "Clic: {name}", "Clic su un comando disattivato: {name}", "{name}: attivo",
           "{name}: disattivo", "{name}: {value}", "Errore imprevisto in {where}: {error}",
           "Finestra aperta: {title}",
           "Aspetto: tema {theme}, accento {accent}, dimensione testo {scale}",
           "Player: {command}", "Barra tempo reale: {command} {value}",
           "Ascolto voce {voice}: {state}", "in preparazione", "in riproduzione", "finito"),
    "ar": ("بدأ Video Translator AI: Python {py}، {os}",
           "ملف السجل (يُحتفظ بآخر {days} أيام): {path}",
           "نقر: {name}", "نقر على عنصر معطّل: {name}", "{name}: مفعّل", "{name}: معطّل",
           "{name}: {value}", "خطأ غير متوقع في {where}: {error}", "نافذة مفتوحة: {title}",
           "المظهر: السمة {theme}، اللون {accent}، حجم النص {scale}",
           "المشغّل: {command}", "شريط الوقت الفعلي: {command} {value}",
           "معاينة الصوت {voice}: {state}", "قيد التحضير", "قيد التشغيل", "انتهى"),
    "zh": ("Video Translator AI 已启动：Python {py}，{os}",
           "日志文件（保留最近 {days} 天）：{path}",
           "点击：{name}", "点击了已禁用的控件：{name}", "{name}：开", "{name}：关",
           "{name}：{value}", "{where} 中出现意外错误：{error}", "已打开窗口：{title}",
           "外观：主题 {theme}，强调色 {accent}，文字大小 {scale}",
           "播放器：{command}", "实时栏：{command} {value}",
           "试听语音 {voice}：{state}", "准备中", "播放中", "已结束"),
    "cs": ("Video Translator AI spuštěn: Python {py}, {os}",
           "Soubor protokolu (uchovává se posledních {days} dní): {path}",
           "Klik: {name}", "Klik na neaktivní ovládací prvek: {name}", "{name}: zapnuto",
           "{name}: vypnuto", "{name}: {value}", "Neočekávaná chyba v {where}: {error}",
           "Otevřené okno: {title}",
           "Vzhled: motiv {theme}, zvýraznění {accent}, velikost textu {scale}",
           "Přehrávač: {command}", "Lišta v reálném čase: {command} {value}",
           "Poslech hlasu {voice}: {state}", "připravuje se", "přehrává se", "dokončeno"),
    "da": ("Video Translator AI startet: Python {py}, {os}",
           "Logfil (de seneste {days} dage gemmes): {path}",
           "Klik: {name}", "Klik på et deaktiveret element: {name}", "{name}: til",
           "{name}: fra", "{name}: {value}", "Uventet fejl i {where}: {error}",
           "Vindue åbnet: {title}",
           "Udseende: tema {theme}, accent {accent}, tekststørrelse {scale}",
           "Afspiller: {command}", "Realtidsbjælke: {command} {value}",
           "Stemmeprøve {voice}: {state}", "forberedes", "afspilles", "færdig"),
    "nl": ("Video Translator AI gestart: Python {py}, {os}",
           "Logbestand (de laatste {days} dagen worden bewaard): {path}",
           "Klik: {name}", "Klik op een uitgeschakeld element: {name}", "{name}: aan",
           "{name}: uit", "{name}: {value}", "Onverwachte fout in {where}: {error}",
           "Venster geopend: {title}",
           "Weergave: thema {theme}, accent {accent}, tekstgrootte {scale}",
           "Speler: {command}", "Realtimebalk: {command} {value}",
           "Stemvoorbeeld {voice}: {state}", "wordt voorbereid", "speelt af", "klaar"),
    "fi": ("Video Translator AI käynnistyi: Python {py}, {os}",
           "Lokitiedosto (viimeiset {days} päivää säilytetään): {path}",
           "Napsautus: {name}", "Napsautus pois käytöstä olevaan ohjaimeen: {name}",
           "{name}: päällä", "{name}: pois", "{name}: {value}",
           "Odottamaton virhe kohteessa {where}: {error}", "Ikkuna avattu: {title}",
           "Ulkoasu: teema {theme}, korostus {accent}, tekstin koko {scale}",
           "Soitin: {command}", "Reaaliaikapalkki: {command} {value}",
           "Äänen kuuntelu {voice}: {state}", "valmistellaan", "toistetaan", "valmis"),
    "fr": ("Video Translator AI démarré : Python {py}, {os}",
           "Fichier journal (les {days} derniers jours sont conservés) : {path}",
           "Clic : {name}", "Clic sur une commande désactivée : {name}", "{name} : activé",
           "{name} : désactivé", "{name} : {value}", "Erreur inattendue dans {where} : {error}",
           "Fenêtre ouverte : {title}",
           "Apparence : thème {theme}, accent {accent}, taille du texte {scale}",
           "Lecteur : {command}", "Barre temps réel : {command} {value}",
           "Écoute de la voix {voice} : {state}", "en préparation", "en lecture", "terminée"),
    "de": ("Video Translator AI gestartet: Python {py}, {os}",
           "Protokolldatei (die letzten {days} Tage werden behalten): {path}",
           "Klick: {name}", "Klick auf ein deaktiviertes Element: {name}", "{name}: an",
           "{name}: aus", "{name}: {value}", "Unerwarteter Fehler in {where}: {error}",
           "Fenster geöffnet: {title}",
           "Darstellung: Design {theme}, Akzent {accent}, Textgröße {scale}",
           "Player: {command}", "Echtzeitleiste: {command} {value}",
           "Stimmprobe {voice}: {state}", "wird vorbereitet", "wird abgespielt", "beendet"),
    "el": ("Το Video Translator AI ξεκίνησε: Python {py}, {os}",
           "Αρχείο καταγραφής (κρατούνται οι τελευταίες {days} ημέρες): {path}",
           "Κλικ: {name}", "Κλικ σε ανενεργό στοιχείο: {name}", "{name}: ενεργό",
           "{name}: ανενεργό", "{name}: {value}", "Απρόσμενο σφάλμα στο {where}: {error}",
           "Άνοιξε παράθυρο: {title}",
           "Εμφάνιση: θέμα {theme}, χρώμα έμφασης {accent}, μέγεθος κειμένου {scale}",
           "Πρόγραμμα αναπαραγωγής: {command}", "Γραμμή πραγματικού χρόνου: {command} {value}",
           "Ακρόαση φωνής {voice}: {state}", "προετοιμάζεται", "αναπαράγεται", "ολοκληρώθηκε"),
    "hi": ("Video Translator AI शुरू हुआ: Python {py}, {os}",
           "लॉग फ़ाइल (पिछले {days} दिन रखे जाते हैं): {path}",
           "क्लिक: {name}", "निष्क्रिय नियंत्रण पर क्लिक: {name}", "{name}: चालू",
           "{name}: बंद", "{name}: {value}", "{where} में अनपेक्षित त्रुटि: {error}",
           "विंडो खुली: {title}",
           "रूप: थीम {theme}, एक्सेंट {accent}, टेक्स्ट आकार {scale}",
           "प्लेयर: {command}", "रीयल-टाइम बार: {command} {value}",
           "आवाज़ पूर्वावलोकन {voice}: {state}", "तैयार हो रहा है", "चल रहा है", "समाप्त"),
    "hu": ("A Video Translator AI elindult: Python {py}, {os}",
           "Naplófájl (az utolsó {days} nap marad meg): {path}",
           "Kattintás: {name}", "Kattintás letiltott vezérlőre: {name}", "{name}: be",
           "{name}: ki", "{name}: {value}", "Váratlan hiba itt: {where}: {error}",
           "Megnyitott ablak: {title}",
           "Megjelenés: téma {theme}, kiemelés {accent}, szövegméret {scale}",
           "Lejátszó: {command}", "Valós idejű sáv: {command} {value}",
           "Hangminta {voice}: {state}", "előkészítés", "lejátszás", "befejezve"),
    "id": ("Video Translator AI dimulai: Python {py}, {os}",
           "Berkas log ({days} hari terakhir disimpan): {path}",
           "Klik: {name}", "Klik pada kontrol nonaktif: {name}", "{name}: aktif",
           "{name}: nonaktif", "{name}: {value}", "Kesalahan tak terduga di {where}: {error}",
           "Jendela dibuka: {title}",
           "Tampilan: tema {theme}, aksen {accent}, ukuran teks {scale}",
           "Pemutar: {command}", "Bilah waktu nyata: {command} {value}",
           "Pratinjau suara {voice}: {state}", "sedang disiapkan", "sedang diputar", "selesai"),
    "ja": ("Video Translator AI を起動しました：Python {py}、{os}",
           "ログファイル（直近 {days} 日分を保存）：{path}",
           "クリック：{name}", "無効なコントロールをクリック：{name}", "{name}：オン",
           "{name}：オフ", "{name}：{value}", "{where} で予期しないエラー：{error}",
           "ウィンドウを開きました：{title}",
           "外観：テーマ {theme}、アクセント {accent}、文字サイズ {scale}",
           "プレーヤー：{command}", "リアルタイムバー：{command} {value}",
           "音声の試聴 {voice}：{state}", "準備中", "再生中", "終了"),
    "ko": ("Video Translator AI 시작: Python {py}, {os}",
           "로그 파일(최근 {days}일 보관): {path}",
           "클릭: {name}", "비활성 컨트롤 클릭: {name}", "{name}: 켬", "{name}: 끔",
           "{name}: {value}", "{where}에서 예기치 않은 오류: {error}", "창 열림: {title}",
           "모양: 테마 {theme}, 강조색 {accent}, 글자 크기 {scale}",
           "플레이어: {command}", "실시간 막대: {command} {value}",
           "음성 미리 듣기 {voice}: {state}", "준비 중", "재생 중", "완료"),
    "no": ("Video Translator AI startet: Python {py}, {os}",
           "Loggfil (de siste {days} dagene beholdes): {path}",
           "Klikk: {name}", "Klikk på en deaktivert kontroll: {name}", "{name}: på",
           "{name}: av", "{name}: {value}", "Uventet feil i {where}: {error}",
           "Vindu åpnet: {title}",
           "Utseende: tema {theme}, aksent {accent}, tekststørrelse {scale}",
           "Spiller: {command}", "Sanntidslinje: {command} {value}",
           "Stemmeprøve {voice}: {state}", "forberedes", "spilles av", "ferdig"),
    "pl": ("Uruchomiono Video Translator AI: Python {py}, {os}",
           "Plik dziennika (przechowywane są ostatnie {days} dni): {path}",
           "Kliknięcie: {name}", "Kliknięcie nieaktywnego elementu: {name}", "{name}: wł.",
           "{name}: wył.", "{name}: {value}", "Nieoczekiwany błąd w {where}: {error}",
           "Otwarto okno: {title}",
           "Wygląd: motyw {theme}, akcent {accent}, rozmiar tekstu {scale}",
           "Odtwarzacz: {command}", "Pasek czasu rzeczywistego: {command} {value}",
           "Odsłuch głosu {voice}: {state}", "przygotowanie", "odtwarzanie", "zakończono"),
    "pt": ("Video Translator AI iniciado: Python {py}, {os}",
           "Ficheiro de registo (guardam-se os últimos {days} dias): {path}",
           "Clique: {name}", "Clique num controlo desativado: {name}", "{name}: ligado",
           "{name}: desligado", "{name}: {value}", "Erro inesperado em {where}: {error}",
           "Janela aberta: {title}",
           "Aspeto: tema {theme}, destaque {accent}, tamanho do texto {scale}",
           "Leitor: {command}", "Barra em tempo real: {command} {value}",
           "Pré-escuta da voz {voice}: {state}", "a preparar", "a reproduzir", "terminada"),
    "ro": ("Video Translator AI a pornit: Python {py}, {os}",
           "Fișier jurnal (se păstrează ultimele {days} zile): {path}",
           "Clic: {name}", "Clic pe o comandă dezactivată: {name}", "{name}: activat",
           "{name}: dezactivat", "{name}: {value}", "Eroare neașteptată în {where}: {error}",
           "Fereastră deschisă: {title}",
           "Aspect: temă {theme}, accent {accent}, dimensiune text {scale}",
           "Player: {command}", "Bara în timp real: {command} {value}",
           "Ascultare voce {voice}: {state}", "în pregătire", "în redare", "terminată"),
    "ru": ("Video Translator AI запущен: Python {py}, {os}",
           "Файл журнала (хранятся последние {days} дней): {path}",
           "Щелчок: {name}", "Щелчок по неактивному элементу: {name}", "{name}: вкл.",
           "{name}: выкл.", "{name}: {value}", "Непредвиденная ошибка в {where}: {error}",
           "Открыто окно: {title}",
           "Оформление: тема {theme}, акцент {accent}, размер текста {scale}",
           "Плеер: {command}", "Панель реального времени: {command} {value}",
           "Прослушивание голоса {voice}: {state}", "подготовка", "воспроизведение",
           "завершено"),
    "es": ("Video Translator AI iniciado: Python {py}, {os}",
           "Archivo de registro (se conservan los últimos {days} días): {path}",
           "Clic: {name}", "Clic en un control desactivado: {name}", "{name}: activado",
           "{name}: desactivado", "{name}: {value}", "Error inesperado en {where}: {error}",
           "Ventana abierta: {title}",
           "Apariencia: tema {theme}, acento {accent}, tamaño del texto {scale}",
           "Reproductor: {command}", "Barra en tiempo real: {command} {value}",
           "Escucha de la voz {voice}: {state}", "preparando", "reproduciendo", "terminada"),
    "sv": ("Video Translator AI startad: Python {py}, {os}",
           "Loggfil (de senaste {days} dagarna sparas): {path}",
           "Klick: {name}", "Klick på en inaktiverad kontroll: {name}", "{name}: på",
           "{name}: av", "{name}: {value}", "Oväntat fel i {where}: {error}",
           "Fönster öppnat: {title}",
           "Utseende: tema {theme}, accent {accent}, textstorlek {scale}",
           "Spelare: {command}", "Realtidsfält: {command} {value}",
           "Röstprov {voice}: {state}", "förbereds", "spelas upp", "klar"),
    "tr": ("Video Translator AI başlatıldı: Python {py}, {os}",
           "Günlük dosyası (son {days} gün saklanır): {path}",
           "Tıklama: {name}", "Devre dışı denetime tıklama: {name}", "{name}: açık",
           "{name}: kapalı", "{name}: {value}", "{where} içinde beklenmeyen hata: {error}",
           "Pencere açıldı: {title}",
           "Görünüm: tema {theme}, vurgu {accent}, metin boyutu {scale}",
           "Oynatıcı: {command}", "Gerçek zamanlı çubuk: {command} {value}",
           "Ses önizleme {voice}: {state}", "hazırlanıyor", "oynatılıyor", "bitti"),
    "uk": ("Video Translator AI запущено: Python {py}, {os}",
           "Файл журналу (зберігаються останні {days} днів): {path}",
           "Клацання: {name}", "Клацання по неактивному елементу: {name}", "{name}: увімк.",
           "{name}: вимк.", "{name}: {value}", "Неочікувана помилка в {where}: {error}",
           "Відкрито вікно: {title}",
           "Вигляд: тема {theme}, акцент {accent}, розмір тексту {scale}",
           "Плеєр: {command}", "Панель реального часу: {command} {value}",
           "Прослуховування голосу {voice}: {state}", "підготовка", "відтворення",
           "завершено"),
    "vi": ("Video Translator AI đã khởi động: Python {py}, {os}",
           "Tệp nhật ký (giữ {days} ngày gần nhất): {path}",
           "Nhấp: {name}", "Nhấp vào điều khiển bị tắt: {name}", "{name}: bật",
           "{name}: tắt", "{name}: {value}", "Lỗi không mong muốn trong {where}: {error}",
           "Đã mở cửa sổ: {title}",
           "Giao diện: chủ đề {theme}, màu nhấn {accent}, cỡ chữ {scale}",
           "Trình phát: {command}", "Thanh thời gian thực: {command} {value}",
           "Nghe thử giọng {voice}: {state}", "đang chuẩn bị", "đang phát", "đã xong"),
}

LOG_UI_STRINGS: dict[str, dict[str, str]] = {
    lang: dict(zip(_KEYS, values)) for lang, values in _T.items()
}


def merge_into(ui_strings: dict[str, dict[str, str]]) -> list[str]:
    """Add these strings to ``ui_strings`` in place; return the problems found."""
    problems: list[str] = []
    for lang, values in _T.items():
        if len(values) != len(_KEYS):
            problems.append(f"{lang}: {len(values)} strings for {len(_KEYS)} keys")
    for lang, entries in LOG_UI_STRINGS.items():
        bucket = ui_strings.get(lang)
        if bucket is None:
            problems.append(f"unknown language {lang!r}")
            continue
        for key, value in entries.items():
            existing = bucket.get(key)
            if existing is not None and existing != value:
                problems.append(f"collision {lang}.{key}")
                continue
            bucket[key] = value
    return problems
