"""UI strings of the integrated player and of live mode (spec 2.6, operator decision Q5).

They live here instead of in video_translator_gui.py so the GUI file does not
grow by thousands of lines; the GUI merges them into UI_STRINGS at import, so
UI_STRINGS stays the single runtime dictionary and App._s keeps its
it -> en -> key fallback. Keys land with the phase that uses them.

Placeholders ({version}, {cmd}, {detail}, {size}, {license}) must be the same
in every language (tests/test_ui_i18n_coverage.py checks it). Brand names
(mpv, libmpv, python-mpv, Vulkan, setup_windows.bat) are not translated.
"""

from __future__ import annotations

PLAYER_UI_STRINGS: dict[str, dict[str, str]] = {
    "it": {
        "player_badge": "Player",
        "player_badge_ok": "Player pronto (mpv {version})",
        "player_unavailable_title": "Player integrato non disponibile",
        "player_missing_pymod": "Il pacchetto python-mpv non è installato.",
        "player_missing_libmpv_linux": "libmpv non è installata. Installala con: {cmd}",
        "player_missing_libmpv_win": "libmpv non è installata. Esegui setup_windows.bat (Repair) oppure installala ora.",
        "player_libmpv_too_old": "La libmpv installata ({version}) è troppo vecchia: serve la 0.34 o successiva.",
        "player_libmpv_load_failed": "Impossibile caricare libmpv ({detail}). Il file potrebbe essere danneggiato o bloccato dall'antivirus.",
        "player_vulkan_missing": "libmpv richiede il runtime Vulkan (vulkan-1.dll): aggiorna il driver grafico o reinstalla il player.",
        "player_probe_crashed": "libmpv si è arrestata in modo anomalo durante il caricamento: il player resta disattivato. Vedi il log.",
        "player_restart_required": "Riavvia l'applicazione per completare l'attivazione del player.",
        "player_install_btn": "Installa player",
        "player_install_confirm": "Scaricare e installare i componenti del player video (circa {size} MB)?",
        "player_installing": "Installazione del player...",
        "player_install_ok": "Player installato.",
        "player_install_failed": "Installazione del player non riuscita: vedi il log.",
        "player_credits": "Riproduzione video: mpv (libmpv), {license}",
        "player_license_system": "libreria di sistema",
        "live_err_busy_install": "È in corso un'installazione: attendi che finisca.",
        "player_playlist_sources": "Sorgenti",
        "player_playlist_results": "Risultati",
        "player_idle_hint": "Seleziona un video nell'elenco Input per visualizzarne qui l'anteprima",
        "player_initializing": "Avvio del player...",
        "player_now_playing": "In riproduzione: {name}",
        "player_nothing_loaded": "Nessun video caricato",
        "player_btn_playlist": "Playlist",
        "player_playlist_empty": "La playlist è vuota",
        "player_tip_previous": "Precedente (P)",
        "player_tip_rewind": "Indietro di 10 s (Sinistra)",
        "player_tip_stop": "Stop",
        "player_tip_play": "Riproduci (Spazio)",
        "player_tip_pause": "Pausa (Spazio)",
        "player_tip_forward": "Avanti di 10 s (Destra)",
        "player_tip_next": "Successivo (N)",
        "player_tip_snapshot": "Salva un'istantanea del fotogramma corrente (S)",
        "player_tip_open_folder": "Apri la cartella di questo video (O)",
        "player_tip_mute": "Disattiva audio (M)",
        "player_tip_unmute": "Riattiva audio (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Schermo intero (F)",
        "player_tip_exit_fullscreen": "Esci da schermo intero (Esc)",
        "player_snapshot_saved": "Istantanea salvata: {path}",
        "player_snapshot_failed": "Impossibile salvare l'istantanea",
        "player_err_load": "Impossibile riprodurre questo file: {name}",
        "player_err_video_output": "Impossibile avviare l'uscita video su questo sistema.",
        "player_vo_fallback_used": "L'uscita video hardware non ha funzionato: uso un'alternativa più lenta.",
        "player_busy": "Il player è occupato, attendi.",
        "player_tip_results_busy": "I risultati potranno essere aperti al termine del lavoro in corso",
        "settings_player": "Player",
        "opt_player_autoload": "Carica automaticamente nel player i video tradotti",
        "opt_keep_original_audio": "Includi l'audio originale come traccia alternativa",
    },
    "en": {
        "player_badge": "Player",
        "player_badge_ok": "Player ready (mpv {version})",
        "player_unavailable_title": "Integrated player not available",
        "player_missing_pymod": "The python-mpv package is not installed.",
        "player_missing_libmpv_linux": "libmpv is not installed. Install it with: {cmd}",
        "player_missing_libmpv_win": "libmpv is not installed. Run setup_windows.bat (Repair) or install it now.",
        "player_libmpv_too_old": "The installed libmpv ({version}) is too old: 0.34 or newer is needed.",
        "player_libmpv_load_failed": "libmpv could not be loaded ({detail}). The file may be damaged or blocked by the antivirus.",
        "player_vulkan_missing": "libmpv needs the Vulkan runtime (vulkan-1.dll): update the graphics driver or install the player again.",
        "player_probe_crashed": "libmpv crashed while loading: the player stays disabled. See the log.",
        "player_restart_required": "Restart the application to finish enabling the player.",
        "player_install_btn": "Install player",
        "player_install_confirm": "Download and install the video player components (about {size} MB)?",
        "player_installing": "Installing the player...",
        "player_install_ok": "Player installed.",
        "player_install_failed": "Player installation failed: see the log.",
        "player_credits": "Video playback: mpv (libmpv), {license}",
        "player_license_system": "system library",
        "live_err_busy_install": "An installation is running: wait for it to finish.",
        "player_playlist_sources": "Sources",
        "player_playlist_results": "Results",
        "player_idle_hint": "Select a video in the Input list to preview it here",
        "player_initializing": "Starting the player...",
        "player_now_playing": "Now playing: {name}",
        "player_nothing_loaded": "No video loaded",
        "player_btn_playlist": "Playlist",
        "player_playlist_empty": "The playlist is empty",
        "player_tip_previous": "Previous (P)",
        "player_tip_rewind": "Back 10 s (Left)",
        "player_tip_stop": "Stop",
        "player_tip_play": "Play (Space)",
        "player_tip_pause": "Pause (Space)",
        "player_tip_forward": "Forward 10 s (Right)",
        "player_tip_next": "Next (N)",
        "player_tip_snapshot": "Save a snapshot of the current frame (S)",
        "player_tip_open_folder": "Open the folder of this video (O)",
        "player_tip_mute": "Mute (M)",
        "player_tip_unmute": "Unmute (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Full screen (F)",
        "player_tip_exit_fullscreen": "Exit full screen (Esc)",
        "player_snapshot_saved": "Snapshot saved: {path}",
        "player_snapshot_failed": "Could not save the snapshot",
        "player_err_load": "Cannot play this file: {name}",
        "player_err_video_output": "The video output could not start on this system.",
        "player_vo_fallback_used": "Hardware video output failed: using a slower fallback.",
        "player_busy": "The player is busy, please wait.",
        "player_tip_results_busy": "Results can be opened when the running job ends",
        "settings_player": "Player",
        "opt_player_autoload": "Automatically load translated videos in the player",
        "opt_keep_original_audio": "Include the original audio as an alternate track",
    },
    "ar": {
        "player_badge": "المشغل",
        "player_badge_ok": "المشغل جاهز (mpv {version})",
        "player_unavailable_title": "المشغل المدمج غير متاح",
        "player_missing_pymod": "حزمة python-mpv غير مثبتة.",
        "player_missing_libmpv_linux": "مكتبة libmpv غير مثبتة. ثبّتها باستخدام: {cmd}",
        "player_missing_libmpv_win": "مكتبة libmpv غير مثبتة. شغّل setup_windows.bat (Repair) أو ثبّتها الآن.",
        "player_libmpv_too_old": "إصدار libmpv المثبت ({version}) قديم جدًا: يلزم الإصدار 0.34 أو أحدث.",
        "player_libmpv_load_failed": "تعذّر تحميل libmpv ({detail}). قد يكون الملف تالفًا أو محظورًا من برنامج مكافحة الفيروسات.",
        "player_vulkan_missing": "تحتاج libmpv إلى بيئة تشغيل Vulkan (vulkan-1.dll): حدّث برنامج تشغيل الرسومات أو أعد تثبيت المشغل.",
        "player_probe_crashed": "تعطلت libmpv أثناء التحميل: سيبقى المشغل معطّلًا. راجع السجل.",
        "player_restart_required": "أعد تشغيل التطبيق لإكمال تفعيل المشغل.",
        "player_install_btn": "تثبيت المشغل",
        "player_install_confirm": "هل تريد تنزيل مكونات مشغل الفيديو وتثبيتها (حوالي {size} ميغابايت)؟",
        "player_installing": "جارٍ تثبيت المشغل...",
        "player_install_ok": "تم تثبيت المشغل.",
        "player_install_failed": "فشل تثبيت المشغل: راجع السجل.",
        "player_credits": "تشغيل الفيديو: mpv (libmpv)، {license}",
        "player_license_system": "مكتبة النظام",
        "live_err_busy_install": "هناك عملية تثبيت جارية: انتظر حتى تنتهي.",
        "player_playlist_sources": "المصادر",
        "player_playlist_results": "النتائج",
        "player_idle_hint": "اختر فيديو من قائمة الإدخال لمعاينته هنا",
        "player_initializing": "جارٍ تشغيل المشغل...",
        "player_now_playing": "قيد التشغيل الآن: {name}",
        "player_nothing_loaded": "لم يتم تحميل أي فيديو",
        "player_btn_playlist": "قائمة التشغيل",
        "player_playlist_empty": "قائمة التشغيل فارغة",
        "player_tip_previous": "السابق (P)",
        "player_tip_rewind": "رجوع 10 ثوانٍ (السهم الأيسر)",
        "player_tip_stop": "إيقاف",
        "player_tip_play": "تشغيل (مسافة)",
        "player_tip_pause": "إيقاف مؤقت (مسافة)",
        "player_tip_forward": "تقديم 10 ثوانٍ (السهم الأيمن)",
        "player_tip_next": "التالي (N)",
        "player_tip_snapshot": "حفظ لقطة للإطار الحالي (S)",
        "player_tip_open_folder": "فتح مجلد هذا الفيديو (O)",
        "player_tip_mute": "كتم الصوت (M)",
        "player_tip_unmute": "إلغاء كتم الصوت (M)",
        "player_tip_volume": "مستوى الصوت",
        "player_tip_fullscreen": "ملء الشاشة (F)",
        "player_tip_exit_fullscreen": "الخروج من ملء الشاشة (Esc)",
        "player_snapshot_saved": "تم حفظ اللقطة: {path}",
        "player_snapshot_failed": "تعذّر حفظ اللقطة",
        "player_err_load": "تعذّر تشغيل هذا الملف: {name}",
        "player_err_video_output": "تعذّر تشغيل إخراج الفيديو على هذا النظام.",
        "player_vo_fallback_used": "فشل إخراج الفيديو عبر العتاد: جارٍ استخدام بديل أبطأ.",
        "player_busy": "المشغل مشغول، يُرجى الانتظار.",
        "player_tip_results_busy": "يمكن فتح النتائج عند انتهاء المهمة الجارية",
    },
    "zh": {
        "player_badge": "播放器",
        "player_badge_ok": "播放器已就绪 (mpv {version})",
        "player_unavailable_title": "内置播放器不可用",
        "player_missing_pymod": "未安装 python-mpv 软件包。",
        "player_missing_libmpv_linux": "未安装 libmpv。请使用以下命令安装: {cmd}",
        "player_missing_libmpv_win": "未安装 libmpv。请运行 setup_windows.bat (Repair) 或立即安装。",
        "player_libmpv_too_old": "已安装的 libmpv ({version}) 版本过旧: 需要 0.34 或更高版本。",
        "player_libmpv_load_failed": "无法加载 libmpv ({detail})。文件可能已损坏或被杀毒软件拦截。",
        "player_vulkan_missing": "libmpv 需要 Vulkan 运行时 (vulkan-1.dll): 请更新显卡驱动或重新安装播放器。",
        "player_probe_crashed": "libmpv 在加载时崩溃: 播放器保持禁用。请查看日志。",
        "player_restart_required": "请重新启动应用程序以完成播放器的启用。",
        "player_install_btn": "安装播放器",
        "player_install_confirm": "是否下载并安装视频播放器组件 (约 {size} MB)？",
        "player_installing": "正在安装播放器...",
        "player_install_ok": "播放器已安装。",
        "player_install_failed": "播放器安装失败: 请查看日志。",
        "player_credits": "视频播放: mpv (libmpv), {license}",
        "player_license_system": "系统库",
        "live_err_busy_install": "正在进行安装: 请等待其完成。",
        "player_playlist_sources": "源文件",
        "player_playlist_results": "结果",
        "player_idle_hint": "从输入列表中选择一个视频以在此预览",
        "player_initializing": "正在启动播放器...",
        "player_now_playing": "正在播放: {name}",
        "player_nothing_loaded": "未加载视频",
        "player_btn_playlist": "播放列表",
        "player_playlist_empty": "播放列表为空",
        "player_tip_previous": "上一个 (P)",
        "player_tip_rewind": "后退 10 秒 (左箭头)",
        "player_tip_stop": "停止",
        "player_tip_play": "播放 (空格键)",
        "player_tip_pause": "暂停 (空格键)",
        "player_tip_forward": "前进 10 秒 (右箭头)",
        "player_tip_next": "下一个 (N)",
        "player_tip_snapshot": "保存当前画面的截图 (S)",
        "player_tip_open_folder": "打开此视频所在的文件夹 (O)",
        "player_tip_mute": "静音 (M)",
        "player_tip_unmute": "取消静音 (M)",
        "player_tip_volume": "音量",
        "player_tip_fullscreen": "全屏 (F)",
        "player_tip_exit_fullscreen": "退出全屏 (Esc)",
        "player_snapshot_saved": "截图已保存: {path}",
        "player_snapshot_failed": "无法保存截图",
        "player_err_load": "无法播放此文件: {name}",
        "player_err_video_output": "无法在此系统上启动视频输出。",
        "player_vo_fallback_used": "硬件视频输出失败: 正在使用速度较慢的备用方式。",
        "player_busy": "播放器正忙，请稍候。",
        "player_tip_results_busy": "当前任务结束后即可打开结果",
    },
    "cs": {
        "player_badge": "Přehrávač",
        "player_badge_ok": "Přehrávač je připraven (mpv {version})",
        "player_unavailable_title": "Vestavěný přehrávač není k dispozici",
        "player_missing_pymod": "Balíček python-mpv není nainstalován.",
        "player_missing_libmpv_linux": "Knihovna libmpv není nainstalována. Nainstalujte ji příkazem: {cmd}",
        "player_missing_libmpv_win": "Knihovna libmpv není nainstalována. Spusťte setup_windows.bat (Repair) nebo ji nainstalujte nyní.",
        "player_libmpv_too_old": "Nainstalovaná knihovna libmpv ({version}) je příliš stará: je potřeba verze 0.34 nebo novější.",
        "player_libmpv_load_failed": "Knihovnu libmpv nelze načíst ({detail}). Soubor může být poškozený nebo blokovaný antivirem.",
        "player_vulkan_missing": "Knihovna libmpv vyžaduje běhové prostředí Vulkan (vulkan-1.dll): aktualizujte ovladač grafické karty nebo přehrávač nainstalujte znovu.",
        "player_probe_crashed": "Knihovna libmpv při načítání spadla: přehrávač zůstává vypnutý. Podívejte se do protokolu.",
        "player_restart_required": "Restartujte aplikaci, aby se aktivace přehrávače dokončila.",
        "player_install_btn": "Nainstalovat přehrávač",
        "player_install_confirm": "Stáhnout a nainstalovat součásti videopřehrávače (přibližně {size} MB)?",
        "player_installing": "Instalace přehrávače...",
        "player_install_ok": "Přehrávač byl nainstalován.",
        "player_install_failed": "Instalace přehrávače selhala: podívejte se do protokolu.",
        "player_credits": "Přehrávání videa: mpv (libmpv), {license}",
        "player_license_system": "systémová knihovna",
        "live_err_busy_install": "Probíhá instalace: počkejte, až skončí.",
        "player_playlist_sources": "Zdroje",
        "player_playlist_results": "Výsledky",
        "player_idle_hint": "Vyberte video v seznamu Vstup a zobrazte zde jeho náhled",
        "player_initializing": "Spouštění přehrávače...",
        "player_now_playing": "Právě se přehrává: {name}",
        "player_nothing_loaded": "Není načteno žádné video",
        "player_btn_playlist": "Seznam stop",
        "player_playlist_empty": "Seznam stop je prázdný",
        "player_tip_previous": "Předchozí (P)",
        "player_tip_rewind": "Zpět o 10 s (šipka vlevo)",
        "player_tip_stop": "Zastavit",
        "player_tip_play": "Přehrát (mezerník)",
        "player_tip_pause": "Pozastavit (mezerník)",
        "player_tip_forward": "Vpřed o 10 s (šipka vpravo)",
        "player_tip_next": "Další (N)",
        "player_tip_snapshot": "Uložit snímek aktuálního obrazu (S)",
        "player_tip_open_folder": "Otevřít složku tohoto videa (O)",
        "player_tip_mute": "Ztlumit (M)",
        "player_tip_unmute": "Zapnout zvuk (M)",
        "player_tip_volume": "Hlasitost",
        "player_tip_fullscreen": "Celá obrazovka (F)",
        "player_tip_exit_fullscreen": "Ukončit celou obrazovku (Esc)",
        "player_snapshot_saved": "Snímek uložen: {path}",
        "player_snapshot_failed": "Snímek se nepodařilo uložit",
        "player_err_load": "Tento soubor nelze přehrát: {name}",
        "player_err_video_output": "Na tomto systému nelze spustit výstup videa.",
        "player_vo_fallback_used": "Hardwarový výstup videa selhal: používá se pomalejší náhradní režim.",
        "player_busy": "Přehrávač je zaneprázdněn, počkejte prosím.",
        "player_tip_results_busy": "Výsledky lze otevřít po dokončení probíhající úlohy",
    },
    "da": {
        "player_badge": "Afspiller",
        "player_badge_ok": "Afspilleren er klar (mpv {version})",
        "player_unavailable_title": "Den indbyggede afspiller er ikke tilgængelig",
        "player_missing_pymod": "Pakken python-mpv er ikke installeret.",
        "player_missing_libmpv_linux": "libmpv er ikke installeret. Installer det med: {cmd}",
        "player_missing_libmpv_win": "libmpv er ikke installeret. Kør setup_windows.bat (Repair), eller installer det nu.",
        "player_libmpv_too_old": "Den installerede libmpv ({version}) er for gammel: version 0.34 eller nyere kræves.",
        "player_libmpv_load_failed": "libmpv kunne ikke indlæses ({detail}). Filen kan være beskadiget eller blokeret af antivirusprogrammet.",
        "player_vulkan_missing": "libmpv kræver Vulkan-runtime (vulkan-1.dll): opdater grafikdriveren, eller installer afspilleren igen.",
        "player_probe_crashed": "libmpv gik ned under indlæsningen: afspilleren forbliver deaktiveret. Se loggen.",
        "player_restart_required": "Genstart programmet for at fuldføre aktiveringen af afspilleren.",
        "player_install_btn": "Installer afspiller",
        "player_install_confirm": "Vil du downloade og installere videoafspillerens komponenter (ca. {size} MB)?",
        "player_installing": "Installerer afspilleren...",
        "player_install_ok": "Afspilleren er installeret.",
        "player_install_failed": "Installationen af afspilleren mislykkedes: se loggen.",
        "player_credits": "Videoafspilning: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installation er i gang: vent, til den er færdig.",
        "player_playlist_sources": "Kilder",
        "player_playlist_results": "Resultater",
        "player_idle_hint": "Vælg en video på listen Input for at se den her",
        "player_initializing": "Starter afspilleren...",
        "player_now_playing": "Afspiller nu: {name}",
        "player_nothing_loaded": "Ingen video indlæst",
        "player_btn_playlist": "Afspilningsliste",
        "player_playlist_empty": "Afspilningslisten er tom",
        "player_tip_previous": "Forrige (P)",
        "player_tip_rewind": "10 s tilbage (venstre pil)",
        "player_tip_stop": "Stop",
        "player_tip_play": "Afspil (mellemrum)",
        "player_tip_pause": "Pause (mellemrum)",
        "player_tip_forward": "10 s frem (højre pil)",
        "player_tip_next": "Næste (N)",
        "player_tip_snapshot": "Gem et billede af det aktuelle videobillede (S)",
        "player_tip_open_folder": "Åbn mappen med denne video (O)",
        "player_tip_mute": "Slå lyden fra (M)",
        "player_tip_unmute": "Slå lyden til (M)",
        "player_tip_volume": "Lydstyrke",
        "player_tip_fullscreen": "Fuld skærm (F)",
        "player_tip_exit_fullscreen": "Afslut fuld skærm (Esc)",
        "player_snapshot_saved": "Billede gemt: {path}",
        "player_snapshot_failed": "Billedet kunne ikke gemmes",
        "player_err_load": "Denne fil kan ikke afspilles: {name}",
        "player_err_video_output": "Videooutput kunne ikke startes på dette system.",
        "player_vo_fallback_used": "Hardwarevideooutput mislykkedes: bruger en langsommere reserve.",
        "player_busy": "Afspilleren er optaget, vent venligst.",
        "player_tip_results_busy": "Resultater kan åbnes, når det igangværende job er færdigt",
    },
    "nl": {
        "player_badge": "Speler",
        "player_badge_ok": "Speler gereed (mpv {version})",
        "player_unavailable_title": "Ingebouwde speler niet beschikbaar",
        "player_missing_pymod": "Het pakket python-mpv is niet geïnstalleerd.",
        "player_missing_libmpv_linux": "libmpv is niet geïnstalleerd. Installeer het met: {cmd}",
        "player_missing_libmpv_win": "libmpv is niet geïnstalleerd. Voer setup_windows.bat (Repair) uit of installeer het nu.",
        "player_libmpv_too_old": "De geïnstalleerde libmpv ({version}) is te oud: versie 0.34 of nieuwer is vereist.",
        "player_libmpv_load_failed": "libmpv kon niet worden geladen ({detail}). Het bestand is mogelijk beschadigd of geblokkeerd door de antivirus.",
        "player_vulkan_missing": "libmpv heeft de Vulkan-runtime nodig (vulkan-1.dll): werk het grafische stuurprogramma bij of installeer de speler opnieuw.",
        "player_probe_crashed": "libmpv is vastgelopen tijdens het laden: de speler blijft uitgeschakeld. Zie het logboek.",
        "player_restart_required": "Start de applicatie opnieuw om het inschakelen van de speler te voltooien.",
        "player_install_btn": "Speler installeren",
        "player_install_confirm": "De onderdelen van de videospeler downloaden en installeren (ongeveer {size} MB)?",
        "player_installing": "Speler wordt geïnstalleerd...",
        "player_install_ok": "Speler geïnstalleerd.",
        "player_install_failed": "Installatie van de speler mislukt: zie het logboek.",
        "player_credits": "Videoweergave: mpv (libmpv), {license}",
        "player_license_system": "systeembibliotheek",
        "live_err_busy_install": "Er loopt een installatie: wacht tot deze klaar is.",
        "player_playlist_sources": "Bronnen",
        "player_playlist_results": "Resultaten",
        "player_idle_hint": "Selecteer een video in de lijst Invoer om hier een voorbeeld te bekijken",
        "player_initializing": "Speler wordt gestart...",
        "player_now_playing": "Wordt nu afgespeeld: {name}",
        "player_nothing_loaded": "Geen video geladen",
        "player_btn_playlist": "Afspeellijst",
        "player_playlist_empty": "De afspeellijst is leeg",
        "player_tip_previous": "Vorige (P)",
        "player_tip_rewind": "10 s terug (pijl links)",
        "player_tip_stop": "Stoppen",
        "player_tip_play": "Afspelen (spatie)",
        "player_tip_pause": "Pauzeren (spatie)",
        "player_tip_forward": "10 s vooruit (pijl rechts)",
        "player_tip_next": "Volgende (N)",
        "player_tip_snapshot": "Momentopname van het huidige beeld opslaan (S)",
        "player_tip_open_folder": "De map van deze video openen (O)",
        "player_tip_mute": "Dempen (M)",
        "player_tip_unmute": "Dempen opheffen (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Volledig scherm (F)",
        "player_tip_exit_fullscreen": "Volledig scherm afsluiten (Esc)",
        "player_snapshot_saved": "Momentopname opgeslagen: {path}",
        "player_snapshot_failed": "Momentopname kon niet worden opgeslagen",
        "player_err_load": "Dit bestand kan niet worden afgespeeld: {name}",
        "player_err_video_output": "De video-uitvoer kon op dit systeem niet worden gestart.",
        "player_vo_fallback_used": "Hardwarematige video-uitvoer is mislukt: er wordt een langzamer alternatief gebruikt.",
        "player_busy": "De speler is bezig. Even geduld.",
        "player_tip_results_busy": "Resultaten kunnen worden geopend wanneer de huidige taak is voltooid",
    },
    "fi": {
        "player_badge": "Soitin",
        "player_badge_ok": "Soitin on valmis (mpv {version})",
        "player_unavailable_title": "Sisäänrakennettu soitin ei ole käytettävissä",
        "player_missing_pymod": "python-mpv-pakettia ei ole asennettu.",
        "player_missing_libmpv_linux": "libmpv-kirjastoa ei ole asennettu. Asenna se komennolla: {cmd}",
        "player_missing_libmpv_win": "libmpv-kirjastoa ei ole asennettu. Suorita setup_windows.bat (Repair) tai asenna se nyt.",
        "player_libmpv_too_old": "Asennettu libmpv ({version}) on liian vanha: tarvitaan versio 0.34 tai uudempi.",
        "player_libmpv_load_failed": "libmpv-kirjastoa ei voitu ladata ({detail}). Tiedosto voi olla vioittunut tai virustorjunnan estämä.",
        "player_vulkan_missing": "libmpv tarvitsee Vulkan-ajonaikaisympäristön (vulkan-1.dll): päivitä näytönohjaimen ajuri tai asenna soitin uudelleen.",
        "player_probe_crashed": "libmpv kaatui latauksen aikana: soitin pysyy poissa käytöstä. Katso loki.",
        "player_restart_required": "Käynnistä sovellus uudelleen, jotta soittimen käyttöönotto valmistuu.",
        "player_install_btn": "Asenna soitin",
        "player_install_confirm": "Ladataanko ja asennetaanko videosoittimen osat (noin {size} Mt)?",
        "player_installing": "Asennetaan soitinta...",
        "player_install_ok": "Soitin asennettu.",
        "player_install_failed": "Soittimen asennus epäonnistui: katso loki.",
        "player_credits": "Videotoisto: mpv (libmpv), {license}",
        "player_license_system": "järjestelmäkirjasto",
        "live_err_busy_install": "Asennus on käynnissä: odota, että se valmistuu.",
        "player_playlist_sources": "Lähteet",
        "player_playlist_results": "Tulokset",
        "player_idle_hint": "Valitse video Syöte-luettelosta, niin sen esikatselu näkyy tässä",
        "player_initializing": "Käynnistetään soitinta...",
        "player_now_playing": "Nyt toistetaan: {name}",
        "player_nothing_loaded": "Videota ei ole ladattu",
        "player_btn_playlist": "Soittolista",
        "player_playlist_empty": "Soittolista on tyhjä",
        "player_tip_previous": "Edellinen (P)",
        "player_tip_rewind": "10 s taaksepäin (vasen nuoli)",
        "player_tip_stop": "Pysäytä",
        "player_tip_play": "Toista (välilyönti)",
        "player_tip_pause": "Keskeytä (välilyönti)",
        "player_tip_forward": "10 s eteenpäin (oikea nuoli)",
        "player_tip_next": "Seuraava (N)",
        "player_tip_snapshot": "Tallenna kuva nykyisestä ruudusta (S)",
        "player_tip_open_folder": "Avaa tämän videon kansio (O)",
        "player_tip_mute": "Mykistä (M)",
        "player_tip_unmute": "Poista mykistys (M)",
        "player_tip_volume": "Äänenvoimakkuus",
        "player_tip_fullscreen": "Koko näyttö (F)",
        "player_tip_exit_fullscreen": "Poistu koko näytön tilasta (Esc)",
        "player_snapshot_saved": "Kuva tallennettu: {path}",
        "player_snapshot_failed": "Kuvan tallentaminen epäonnistui",
        "player_err_load": "Tätä tiedostoa ei voi toistaa: {name}",
        "player_err_video_output": "Videolähtöä ei voitu käynnistää tässä järjestelmässä.",
        "player_vo_fallback_used": "Laitteistopohjainen videolähtö epäonnistui: käytetään hitaampaa varavaihtoehtoa.",
        "player_busy": "Soitin on varattu, odota hetki.",
        "player_tip_results_busy": "Tulokset voidaan avata käynnissä olevan työn valmistuttua",
    },
    "fr": {
        "player_badge": "Lecteur",
        "player_badge_ok": "Lecteur prêt (mpv {version})",
        "player_unavailable_title": "Lecteur intégré indisponible",
        "player_missing_pymod": "Le paquet python-mpv n'est pas installé.",
        "player_missing_libmpv_linux": "libmpv n'est pas installée. Installez-la avec : {cmd}",
        "player_missing_libmpv_win": "libmpv n'est pas installée. Lancez setup_windows.bat (Repair) ou installez-la maintenant.",
        "player_libmpv_too_old": "La libmpv installée ({version}) est trop ancienne : la version 0.34 ou plus récente est requise.",
        "player_libmpv_load_failed": "Impossible de charger libmpv ({detail}). Le fichier est peut-être endommagé ou bloqué par l'antivirus.",
        "player_vulkan_missing": "libmpv a besoin du runtime Vulkan (vulkan-1.dll) : mettez à jour le pilote graphique ou réinstallez le lecteur.",
        "player_probe_crashed": "libmpv a planté pendant le chargement : le lecteur reste désactivé. Consultez le journal.",
        "player_restart_required": "Redémarrez l'application pour terminer l'activation du lecteur.",
        "player_install_btn": "Installer le lecteur",
        "player_install_confirm": "Télécharger et installer les composants du lecteur vidéo (environ {size} Mo) ?",
        "player_installing": "Installation du lecteur...",
        "player_install_ok": "Lecteur installé.",
        "player_install_failed": "L'installation du lecteur a échoué : consultez le journal.",
        "player_credits": "Lecture vidéo : mpv (libmpv), {license}",
        "player_license_system": "bibliothèque système",
        "live_err_busy_install": "Une installation est en cours : attendez qu'elle se termine.",
        "player_playlist_sources": "Sources",
        "player_playlist_results": "Résultats",
        "player_idle_hint": "Sélectionnez une vidéo dans la liste Entrée pour la prévisualiser ici",
        "player_initializing": "Démarrage du lecteur...",
        "player_now_playing": "Lecture en cours : {name}",
        "player_nothing_loaded": "Aucune vidéo chargée",
        "player_btn_playlist": "Liste de lecture",
        "player_playlist_empty": "La liste de lecture est vide",
        "player_tip_previous": "Précédent (P)",
        "player_tip_rewind": "Reculer de 10 s (flèche gauche)",
        "player_tip_stop": "Arrêter",
        "player_tip_play": "Lire (espace)",
        "player_tip_pause": "Pause (espace)",
        "player_tip_forward": "Avancer de 10 s (flèche droite)",
        "player_tip_next": "Suivant (N)",
        "player_tip_snapshot": "Enregistrer une capture de l'image actuelle (S)",
        "player_tip_open_folder": "Ouvrir le dossier de cette vidéo (O)",
        "player_tip_mute": "Couper le son (M)",
        "player_tip_unmute": "Rétablir le son (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Plein écran (F)",
        "player_tip_exit_fullscreen": "Quitter le plein écran (Esc)",
        "player_snapshot_saved": "Capture enregistrée : {path}",
        "player_snapshot_failed": "Impossible d'enregistrer la capture",
        "player_err_load": "Impossible de lire ce fichier : {name}",
        "player_err_video_output": "La sortie vidéo n'a pas pu démarrer sur ce système.",
        "player_vo_fallback_used": "Échec de la sortie vidéo matérielle : utilisation d'une solution de secours plus lente.",
        "player_busy": "Le lecteur est occupé, veuillez patienter.",
        "player_tip_results_busy": "Les résultats pourront être ouverts à la fin de la tâche en cours",
    },
    "de": {
        "player_badge": "Player",
        "player_badge_ok": "Player bereit (mpv {version})",
        "player_unavailable_title": "Integrierter Player nicht verfügbar",
        "player_missing_pymod": "Das Paket python-mpv ist nicht installiert.",
        "player_missing_libmpv_linux": "libmpv ist nicht installiert. Installieren Sie es mit: {cmd}",
        "player_missing_libmpv_win": "libmpv ist nicht installiert. Führen Sie setup_windows.bat (Repair) aus oder installieren Sie es jetzt.",
        "player_libmpv_too_old": "Die installierte libmpv ({version}) ist zu alt: Version 0.34 oder neuer wird benötigt.",
        "player_libmpv_load_failed": "libmpv konnte nicht geladen werden ({detail}). Die Datei ist möglicherweise beschädigt oder vom Virenschutz blockiert.",
        "player_vulkan_missing": "libmpv benötigt die Vulkan-Laufzeitumgebung (vulkan-1.dll): Aktualisieren Sie den Grafiktreiber oder installieren Sie den Player erneut.",
        "player_probe_crashed": "libmpv ist beim Laden abgestürzt: Der Player bleibt deaktiviert. Siehe Protokoll.",
        "player_restart_required": "Starten Sie die Anwendung neu, um die Aktivierung des Players abzuschließen.",
        "player_install_btn": "Player installieren",
        "player_install_confirm": "Die Komponenten des Videoplayers herunterladen und installieren (etwa {size} MB)?",
        "player_installing": "Player wird installiert...",
        "player_install_ok": "Player installiert.",
        "player_install_failed": "Installation des Players fehlgeschlagen: siehe Protokoll.",
        "player_credits": "Videowiedergabe: mpv (libmpv), {license}",
        "player_license_system": "Systembibliothek",
        "live_err_busy_install": "Eine Installation läuft: Warten Sie, bis sie abgeschlossen ist.",
        "player_playlist_sources": "Quellen",
        "player_playlist_results": "Ergebnisse",
        "player_idle_hint": "Wählen Sie ein Video in der Eingabeliste aus, um es hier in der Vorschau anzuzeigen",
        "player_initializing": "Player wird gestartet...",
        "player_now_playing": "Aktuelle Wiedergabe: {name}",
        "player_nothing_loaded": "Kein Video geladen",
        "player_btn_playlist": "Wiedergabeliste",
        "player_playlist_empty": "Die Wiedergabeliste ist leer",
        "player_tip_previous": "Vorheriges (P)",
        "player_tip_rewind": "10 s zurück (Pfeil links)",
        "player_tip_stop": "Stopp",
        "player_tip_play": "Wiedergabe (Leertaste)",
        "player_tip_pause": "Pause (Leertaste)",
        "player_tip_forward": "10 s vor (Pfeil rechts)",
        "player_tip_next": "Nächstes (N)",
        "player_tip_snapshot": "Momentaufnahme des aktuellen Bildes speichern (S)",
        "player_tip_open_folder": "Ordner dieses Videos öffnen (O)",
        "player_tip_mute": "Stummschalten (M)",
        "player_tip_unmute": "Ton einschalten (M)",
        "player_tip_volume": "Lautstärke",
        "player_tip_fullscreen": "Vollbild (F)",
        "player_tip_exit_fullscreen": "Vollbild verlassen (Esc)",
        "player_snapshot_saved": "Momentaufnahme gespeichert: {path}",
        "player_snapshot_failed": "Momentaufnahme konnte nicht gespeichert werden",
        "player_err_load": "Diese Datei kann nicht wiedergegeben werden: {name}",
        "player_err_video_output": "Die Videoausgabe konnte auf diesem System nicht gestartet werden.",
        "player_vo_fallback_used": "Die Hardware-Videoausgabe ist fehlgeschlagen: Eine langsamere Alternative wird verwendet.",
        "player_busy": "Der Player ist beschäftigt, bitte warten.",
        "player_tip_results_busy": "Ergebnisse können nach Abschluss des laufenden Auftrags geöffnet werden",
    },
    "el": {
        "player_badge": "Αναπαραγωγέας",
        "player_badge_ok": "Ο αναπαραγωγέας είναι έτοιμος (mpv {version})",
        "player_unavailable_title": "Ο ενσωματωμένος αναπαραγωγέας δεν είναι διαθέσιμος",
        "player_missing_pymod": "Το πακέτο python-mpv δεν είναι εγκατεστημένο.",
        "player_missing_libmpv_linux": "Η libmpv δεν είναι εγκατεστημένη. Εγκαταστήστε τη με: {cmd}",
        "player_missing_libmpv_win": "Η libmpv δεν είναι εγκατεστημένη. Εκτελέστε το setup_windows.bat (Repair) ή εγκαταστήστε τη τώρα.",
        "player_libmpv_too_old": "Η εγκατεστημένη libmpv ({version}) είναι πολύ παλιά: απαιτείται η έκδοση 0.34 ή νεότερη.",
        "player_libmpv_load_failed": "Δεν ήταν δυνατή η φόρτωση της libmpv ({detail}). Το αρχείο μπορεί να είναι κατεστραμμένο ή να έχει αποκλειστεί από το πρόγραμμα προστασίας από ιούς.",
        "player_vulkan_missing": "Η libmpv χρειάζεται το περιβάλλον εκτέλεσης Vulkan (vulkan-1.dll): ενημερώστε το πρόγραμμα οδήγησης γραφικών ή εγκαταστήστε ξανά τον αναπαραγωγέα.",
        "player_probe_crashed": "Η libmpv κατέρρευσε κατά τη φόρτωση: ο αναπαραγωγέας παραμένει απενεργοποιημένος. Δείτε το ημερολόγιο.",
        "player_restart_required": "Επανεκκινήστε την εφαρμογή για να ολοκληρωθεί η ενεργοποίηση του αναπαραγωγέα.",
        "player_install_btn": "Εγκατάσταση αναπαραγωγέα",
        "player_install_confirm": "Λήψη και εγκατάσταση των στοιχείων του αναπαραγωγέα βίντεο (περίπου {size} MB);",
        "player_installing": "Εγκατάσταση του αναπαραγωγέα...",
        "player_install_ok": "Ο αναπαραγωγέας εγκαταστάθηκε.",
        "player_install_failed": "Η εγκατάσταση του αναπαραγωγέα απέτυχε: δείτε το ημερολόγιο.",
        "player_credits": "Αναπαραγωγή βίντεο: mpv (libmpv), {license}",
        "player_license_system": "βιβλιοθήκη συστήματος",
        "live_err_busy_install": "Εκτελείται μια εγκατάσταση: περιμένετε να ολοκληρωθεί.",
        "player_playlist_sources": "Πηγές",
        "player_playlist_results": "Αποτελέσματα",
        "player_idle_hint": "Επιλέξτε ένα βίντεο από τη λίστα Εισόδου για προεπισκόπηση εδώ",
        "player_initializing": "Εκκίνηση του προγράμματος αναπαραγωγής...",
        "player_now_playing": "Αναπαράγεται τώρα: {name}",
        "player_nothing_loaded": "Δεν έχει φορτωθεί βίντεο",
        "player_btn_playlist": "Λίστα αναπαραγωγής",
        "player_playlist_empty": "Η λίστα αναπαραγωγής είναι κενή",
        "player_tip_previous": "Προηγούμενο (P)",
        "player_tip_rewind": "Πίσω 10 δευτ. (αριστερό βέλος)",
        "player_tip_stop": "Διακοπή",
        "player_tip_play": "Αναπαραγωγή (διάστημα)",
        "player_tip_pause": "Παύση (διάστημα)",
        "player_tip_forward": "Μπροστά 10 δευτ. (δεξί βέλος)",
        "player_tip_next": "Επόμενο (N)",
        "player_tip_snapshot": "Αποθήκευση στιγμιότυπου του τρέχοντος καρέ (S)",
        "player_tip_open_folder": "Άνοιγμα του φακέλου αυτού του βίντεο (O)",
        "player_tip_mute": "Σίγαση (M)",
        "player_tip_unmute": "Κατάργηση σίγασης (M)",
        "player_tip_volume": "Ένταση",
        "player_tip_fullscreen": "Πλήρης οθόνη (F)",
        "player_tip_exit_fullscreen": "Έξοδος από πλήρη οθόνη (Esc)",
        "player_snapshot_saved": "Το στιγμιότυπο αποθηκεύτηκε: {path}",
        "player_snapshot_failed": "Δεν ήταν δυνατή η αποθήκευση του στιγμιότυπου",
        "player_err_load": "Δεν είναι δυνατή η αναπαραγωγή αυτού του αρχείου: {name}",
        "player_err_video_output": "Δεν ήταν δυνατή η εκκίνηση της εξόδου βίντεο σε αυτό το σύστημα.",
        "player_vo_fallback_used": "Η έξοδος βίντεο μέσω υλικού απέτυχε: χρησιμοποιείται πιο αργή εναλλακτική.",
        "player_busy": "Το πρόγραμμα αναπαραγωγής είναι απασχολημένο, περιμένετε.",
        "player_tip_results_busy": "Τα αποτελέσματα μπορούν να ανοίξουν όταν ολοκληρωθεί η τρέχουσα εργασία",
    },
    "hi": {
        "player_badge": "प्लेयर",
        "player_badge_ok": "प्लेयर तैयार है (mpv {version})",
        "player_unavailable_title": "अंतर्निहित प्लेयर उपलब्ध नहीं है",
        "player_missing_pymod": "python-mpv पैकेज इंस्टॉल नहीं है।",
        "player_missing_libmpv_linux": "libmpv इंस्टॉल नहीं है। इसे इस कमांड से इंस्टॉल करें: {cmd}",
        "player_missing_libmpv_win": "libmpv इंस्टॉल नहीं है। setup_windows.bat (Repair) चलाएँ या इसे अभी इंस्टॉल करें।",
        "player_libmpv_too_old": "इंस्टॉल की गई libmpv ({version}) बहुत पुरानी है: 0.34 या नया संस्करण आवश्यक है।",
        "player_libmpv_load_failed": "libmpv लोड नहीं हो सकी ({detail})। फ़ाइल क्षतिग्रस्त हो सकती है या एंटीवायरस ने उसे ब्लॉक किया हो सकता है।",
        "player_vulkan_missing": "libmpv को Vulkan रनटाइम (vulkan-1.dll) चाहिए: ग्राफ़िक्स ड्राइवर अपडेट करें या प्लेयर को फिर से इंस्टॉल करें।",
        "player_probe_crashed": "लोड करते समय libmpv क्रैश हो गई: प्लेयर अक्षम रहेगा। लॉग देखें।",
        "player_restart_required": "प्लेयर को सक्षम करने की प्रक्रिया पूरी करने के लिए एप्लिकेशन को पुनः आरंभ करें।",
        "player_install_btn": "प्लेयर इंस्टॉल करें",
        "player_install_confirm": "वीडियो प्लेयर के घटक डाउनलोड और इंस्टॉल करें (लगभग {size} MB)?",
        "player_installing": "प्लेयर इंस्टॉल हो रहा है...",
        "player_install_ok": "प्लेयर इंस्टॉल हो गया।",
        "player_install_failed": "प्लेयर इंस्टॉल नहीं हो सका: लॉग देखें।",
        "player_credits": "वीडियो प्लेबैक: mpv (libmpv), {license}",
        "player_license_system": "सिस्टम लाइब्रेरी",
        "live_err_busy_install": "एक इंस्टॉलेशन चल रहा है: उसके पूरा होने तक प्रतीक्षा करें।",
        "player_playlist_sources": "स्रोत",
        "player_playlist_results": "परिणाम",
        "player_idle_hint": "यहाँ पूर्वावलोकन करने के लिए इनपुट सूची से कोई वीडियो चुनें",
        "player_initializing": "प्लेयर शुरू हो रहा है...",
        "player_now_playing": "अभी चल रहा है: {name}",
        "player_nothing_loaded": "कोई वीडियो लोड नहीं है",
        "player_btn_playlist": "प्लेलिस्ट",
        "player_playlist_empty": "प्लेलिस्ट खाली है",
        "player_tip_previous": "पिछला (P)",
        "player_tip_rewind": "10 सेकंड पीछे (बायाँ तीर)",
        "player_tip_stop": "रोकें",
        "player_tip_play": "चलाएँ (स्पेस)",
        "player_tip_pause": "विराम (स्पेस)",
        "player_tip_forward": "10 सेकंड आगे (दायाँ तीर)",
        "player_tip_next": "अगला (N)",
        "player_tip_snapshot": "मौजूदा फ़्रेम का स्नैपशॉट सहेजें (S)",
        "player_tip_open_folder": "इस वीडियो का फ़ोल्डर खोलें (O)",
        "player_tip_mute": "आवाज़ बंद करें (M)",
        "player_tip_unmute": "आवाज़ चालू करें (M)",
        "player_tip_volume": "आवाज़",
        "player_tip_fullscreen": "पूर्ण स्क्रीन (F)",
        "player_tip_exit_fullscreen": "पूर्ण स्क्रीन से बाहर निकलें (Esc)",
        "player_snapshot_saved": "स्नैपशॉट सहेजा गया: {path}",
        "player_snapshot_failed": "स्नैपशॉट सहेजा नहीं जा सका",
        "player_err_load": "यह फ़ाइल चलाई नहीं जा सकती: {name}",
        "player_err_video_output": "इस सिस्टम पर वीडियो आउटपुट शुरू नहीं हो सका।",
        "player_vo_fallback_used": "हार्डवेयर वीडियो आउटपुट विफल रहा: धीमे वैकल्पिक तरीके का उपयोग किया जा रहा है।",
        "player_busy": "प्लेयर व्यस्त है, कृपया प्रतीक्षा करें।",
        "player_tip_results_busy": "चल रहा कार्य समाप्त होने पर परिणाम खोले जा सकते हैं",
    },
    "hu": {
        "player_badge": "Lejátszó",
        "player_badge_ok": "A lejátszó kész (mpv {version})",
        "player_unavailable_title": "A beépített lejátszó nem érhető el",
        "player_missing_pymod": "A python-mpv csomag nincs telepítve.",
        "player_missing_libmpv_linux": "A libmpv nincs telepítve. Telepítse ezzel a paranccsal: {cmd}",
        "player_missing_libmpv_win": "A libmpv nincs telepítve. Futtassa a setup_windows.bat fájlt (Repair), vagy telepítse most.",
        "player_libmpv_too_old": "A telepített libmpv ({version}) túl régi: 0.34-es vagy újabb verzió szükséges.",
        "player_libmpv_load_failed": "A libmpv nem tölthető be ({detail}). Lehet, hogy a fájl sérült, vagy a víruskereső blokkolja.",
        "player_vulkan_missing": "A libmpv-nek szüksége van a Vulkan futtatókörnyezetre (vulkan-1.dll): frissítse a grafikus illesztőprogramot, vagy telepítse újra a lejátszót.",
        "player_probe_crashed": "A libmpv betöltés közben összeomlott: a lejátszó letiltva marad. Nézze meg a naplót.",
        "player_restart_required": "Indítsa újra az alkalmazást a lejátszó bekapcsolásának befejezéséhez.",
        "player_install_btn": "Lejátszó telepítése",
        "player_install_confirm": "Letölti és telepíti a videolejátszó összetevőit (kb. {size} MB)?",
        "player_installing": "A lejátszó telepítése...",
        "player_install_ok": "A lejátszó telepítve.",
        "player_install_failed": "A lejátszó telepítése nem sikerült: nézze meg a naplót.",
        "player_credits": "Videolejátszás: mpv (libmpv), {license}",
        "player_license_system": "rendszerkönyvtár",
        "live_err_busy_install": "Telepítés van folyamatban: várja meg, amíg befejeződik.",
        "player_playlist_sources": "Források",
        "player_playlist_results": "Eredmények",
        "player_idle_hint": "Válasszon egy videót a Bemenet listából az itteni előnézethez",
        "player_initializing": "A lejátszó indítása...",
        "player_now_playing": "Most játszott: {name}",
        "player_nothing_loaded": "Nincs betöltött videó",
        "player_btn_playlist": "Lejátszási lista",
        "player_playlist_empty": "A lejátszási lista üres",
        "player_tip_previous": "Előző (P)",
        "player_tip_rewind": "Vissza 10 másodperccel (balra nyíl)",
        "player_tip_stop": "Leállítás",
        "player_tip_play": "Lejátszás (szóköz)",
        "player_tip_pause": "Szünet (szóköz)",
        "player_tip_forward": "Előre 10 másodperccel (jobbra nyíl)",
        "player_tip_next": "Következő (N)",
        "player_tip_snapshot": "Pillanatkép mentése az aktuális képkockáról (S)",
        "player_tip_open_folder": "A videó mappájának megnyitása (O)",
        "player_tip_mute": "Némítás (M)",
        "player_tip_unmute": "Némítás feloldása (M)",
        "player_tip_volume": "Hangerő",
        "player_tip_fullscreen": "Teljes képernyő (F)",
        "player_tip_exit_fullscreen": "Kilépés a teljes képernyőből (Esc)",
        "player_snapshot_saved": "Pillanatkép mentve: {path}",
        "player_snapshot_failed": "A pillanatkép nem menthető",
        "player_err_load": "Ez a fájl nem játszható le: {name}",
        "player_err_video_output": "A videokimenet nem indítható el ezen a rendszeren.",
        "player_vo_fallback_used": "A hardveres videokimenet nem működött: lassabb tartalék mód használata.",
        "player_busy": "A lejátszó foglalt, kérjük, várjon.",
        "player_tip_results_busy": "Az eredmények a futó feladat befejezése után nyithatók meg",
    },
    "id": {
        "player_badge": "Pemutar",
        "player_badge_ok": "Pemutar siap (mpv {version})",
        "player_unavailable_title": "Pemutar bawaan tidak tersedia",
        "player_missing_pymod": "Paket python-mpv belum terpasang.",
        "player_missing_libmpv_linux": "libmpv belum terpasang. Pasang dengan: {cmd}",
        "player_missing_libmpv_win": "libmpv belum terpasang. Jalankan setup_windows.bat (Repair) atau pasang sekarang.",
        "player_libmpv_too_old": "libmpv yang terpasang ({version}) terlalu lama: diperlukan versi 0.34 atau yang lebih baru.",
        "player_libmpv_load_failed": "libmpv tidak dapat dimuat ({detail}). Berkas mungkin rusak atau diblokir oleh antivirus.",
        "player_vulkan_missing": "libmpv memerlukan runtime Vulkan (vulkan-1.dll): perbarui driver grafis atau pasang ulang pemutar.",
        "player_probe_crashed": "libmpv mengalami crash saat dimuat: pemutar tetap dinonaktifkan. Lihat log.",
        "player_restart_required": "Mulai ulang aplikasi untuk menyelesaikan pengaktifan pemutar.",
        "player_install_btn": "Pasang pemutar",
        "player_install_confirm": "Unduh dan pasang komponen pemutar video (sekitar {size} MB)?",
        "player_installing": "Memasang pemutar...",
        "player_install_ok": "Pemutar terpasang.",
        "player_install_failed": "Pemasangan pemutar gagal: lihat log.",
        "player_credits": "Pemutaran video: mpv (libmpv), {license}",
        "player_license_system": "pustaka sistem",
        "live_err_busy_install": "Sedang ada pemasangan: tunggu hingga selesai.",
        "player_playlist_sources": "Sumber",
        "player_playlist_results": "Hasil",
        "player_idle_hint": "Pilih video di daftar Input untuk melihat pratinjaunya di sini",
        "player_initializing": "Memulai pemutar...",
        "player_now_playing": "Sedang diputar: {name}",
        "player_nothing_loaded": "Tidak ada video yang dimuat",
        "player_btn_playlist": "Daftar putar",
        "player_playlist_empty": "Daftar putar kosong",
        "player_tip_previous": "Sebelumnya (P)",
        "player_tip_rewind": "Mundur 10 dtk (panah kiri)",
        "player_tip_stop": "Hentikan",
        "player_tip_play": "Putar (spasi)",
        "player_tip_pause": "Jeda (spasi)",
        "player_tip_forward": "Maju 10 dtk (panah kanan)",
        "player_tip_next": "Berikutnya (N)",
        "player_tip_snapshot": "Simpan cuplikan bingkai saat ini (S)",
        "player_tip_open_folder": "Buka folder video ini (O)",
        "player_tip_mute": "Bisukan (M)",
        "player_tip_unmute": "Bunyikan (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Layar penuh (F)",
        "player_tip_exit_fullscreen": "Keluar dari layar penuh (Esc)",
        "player_snapshot_saved": "Cuplikan disimpan: {path}",
        "player_snapshot_failed": "Cuplikan tidak dapat disimpan",
        "player_err_load": "Berkas ini tidak dapat diputar: {name}",
        "player_err_video_output": "Keluaran video tidak dapat dimulai pada sistem ini.",
        "player_vo_fallback_used": "Keluaran video perangkat keras gagal: menggunakan cadangan yang lebih lambat.",
        "player_busy": "Pemutar sedang sibuk, harap tunggu.",
        "player_tip_results_busy": "Hasil dapat dibuka setelah tugas yang berjalan selesai",
    },
    "ja": {
        "player_badge": "プレーヤー",
        "player_badge_ok": "プレーヤー準備完了 (mpv {version})",
        "player_unavailable_title": "内蔵プレーヤーは利用できません",
        "player_missing_pymod": "python-mpv パッケージがインストールされていません。",
        "player_missing_libmpv_linux": "libmpv がインストールされていません。次のコマンドでインストールしてください: {cmd}",
        "player_missing_libmpv_win": "libmpv がインストールされていません。setup_windows.bat (Repair) を実行するか、今すぐインストールしてください。",
        "player_libmpv_too_old": "インストールされている libmpv ({version}) は古すぎます: 0.34 以降が必要です。",
        "player_libmpv_load_failed": "libmpv を読み込めませんでした ({detail})。ファイルが破損しているか、ウイルス対策ソフトにブロックされている可能性があります。",
        "player_vulkan_missing": "libmpv には Vulkan ランタイム (vulkan-1.dll) が必要です: グラフィックドライバーを更新するか、プレーヤーを再インストールしてください。",
        "player_probe_crashed": "libmpv が読み込み中にクラッシュしました: プレーヤーは無効のままです。ログを確認してください。",
        "player_restart_required": "プレーヤーの有効化を完了するには、アプリケーションを再起動してください。",
        "player_install_btn": "プレーヤーをインストール",
        "player_install_confirm": "ビデオプレーヤーのコンポーネント (約 {size} MB) をダウンロードしてインストールしますか？",
        "player_installing": "プレーヤーをインストール中...",
        "player_install_ok": "プレーヤーをインストールしました。",
        "player_install_failed": "プレーヤーのインストールに失敗しました: ログを確認してください。",
        "player_credits": "動画再生: mpv (libmpv), {license}",
        "player_license_system": "システムライブラリ",
        "live_err_busy_install": "インストールを実行中です: 完了するまでお待ちください。",
        "player_playlist_sources": "ソース",
        "player_playlist_results": "結果",
        "player_idle_hint": "入力リストから動画を選ぶと、ここでプレビューできます",
        "player_initializing": "プレーヤーを起動しています...",
        "player_now_playing": "再生中: {name}",
        "player_nothing_loaded": "動画が読み込まれていません",
        "player_btn_playlist": "プレイリスト",
        "player_playlist_empty": "プレイリストは空です",
        "player_tip_previous": "前へ (P)",
        "player_tip_rewind": "10 秒戻る (左矢印)",
        "player_tip_stop": "停止",
        "player_tip_play": "再生 (スペース)",
        "player_tip_pause": "一時停止 (スペース)",
        "player_tip_forward": "10 秒進む (右矢印)",
        "player_tip_next": "次へ (N)",
        "player_tip_snapshot": "現在のフレームを画像として保存 (S)",
        "player_tip_open_folder": "この動画のフォルダーを開く (O)",
        "player_tip_mute": "ミュート (M)",
        "player_tip_unmute": "ミュート解除 (M)",
        "player_tip_volume": "音量",
        "player_tip_fullscreen": "全画面表示 (F)",
        "player_tip_exit_fullscreen": "全画面表示を終了 (Esc)",
        "player_snapshot_saved": "画像を保存しました: {path}",
        "player_snapshot_failed": "画像を保存できませんでした",
        "player_err_load": "このファイルを再生できません: {name}",
        "player_err_video_output": "このシステムでは映像出力を開始できませんでした。",
        "player_vo_fallback_used": "ハードウェア映像出力に失敗したため、低速な代替方式を使用します。",
        "player_busy": "プレーヤーは処理中です。しばらくお待ちください。",
        "player_tip_results_busy": "実行中の処理が終了すると結果を開けます",
    },
    "ko": {
        "player_badge": "플레이어",
        "player_badge_ok": "플레이어 준비 완료 (mpv {version})",
        "player_unavailable_title": "내장 플레이어를 사용할 수 없습니다",
        "player_missing_pymod": "python-mpv 패키지가 설치되어 있지 않습니다.",
        "player_missing_libmpv_linux": "libmpv가 설치되어 있지 않습니다. 다음 명령으로 설치하세요: {cmd}",
        "player_missing_libmpv_win": "libmpv가 설치되어 있지 않습니다. setup_windows.bat (Repair)를 실행하거나 지금 설치하세요.",
        "player_libmpv_too_old": "설치된 libmpv ({version})가 너무 오래되었습니다: 0.34 이상이 필요합니다.",
        "player_libmpv_load_failed": "libmpv를 불러올 수 없습니다 ({detail}). 파일이 손상되었거나 백신 프로그램에 의해 차단되었을 수 있습니다.",
        "player_vulkan_missing": "libmpv에는 Vulkan 런타임 (vulkan-1.dll)이 필요합니다: 그래픽 드라이버를 업데이트하거나 플레이어를 다시 설치하세요.",
        "player_probe_crashed": "libmpv가 로드 중에 충돌했습니다: 플레이어가 비활성화된 상태로 유지됩니다. 로그를 확인하세요.",
        "player_restart_required": "플레이어 활성화를 완료하려면 애플리케이션을 다시 시작하세요.",
        "player_install_btn": "플레이어 설치",
        "player_install_confirm": "비디오 플레이어 구성 요소를 다운로드하여 설치할까요 (약 {size} MB)?",
        "player_installing": "플레이어 설치 중...",
        "player_install_ok": "플레이어가 설치되었습니다.",
        "player_install_failed": "플레이어 설치에 실패했습니다: 로그를 확인하세요.",
        "player_credits": "동영상 재생: mpv (libmpv), {license}",
        "player_license_system": "시스템 라이브러리",
        "live_err_busy_install": "설치가 진행 중입니다: 완료될 때까지 기다리세요.",
        "player_playlist_sources": "소스",
        "player_playlist_results": "결과",
        "player_idle_hint": "여기에서 미리 보려면 입력 목록에서 동영상을 선택하세요",
        "player_initializing": "플레이어를 시작하는 중...",
        "player_now_playing": "현재 재생 중: {name}",
        "player_nothing_loaded": "불러온 동영상 없음",
        "player_btn_playlist": "재생 목록",
        "player_playlist_empty": "재생 목록이 비어 있습니다",
        "player_tip_previous": "이전 (P)",
        "player_tip_rewind": "10초 뒤로 (왼쪽 화살표)",
        "player_tip_stop": "정지",
        "player_tip_play": "재생 (스페이스바)",
        "player_tip_pause": "일시 정지 (스페이스바)",
        "player_tip_forward": "10초 앞으로 (오른쪽 화살표)",
        "player_tip_next": "다음 (N)",
        "player_tip_snapshot": "현재 프레임의 스냅샷 저장 (S)",
        "player_tip_open_folder": "이 동영상의 폴더 열기 (O)",
        "player_tip_mute": "음소거 (M)",
        "player_tip_unmute": "음소거 해제 (M)",
        "player_tip_volume": "볼륨",
        "player_tip_fullscreen": "전체 화면 (F)",
        "player_tip_exit_fullscreen": "전체 화면 종료 (Esc)",
        "player_snapshot_saved": "스냅샷 저장됨: {path}",
        "player_snapshot_failed": "스냅샷을 저장할 수 없습니다",
        "player_err_load": "이 파일을 재생할 수 없습니다: {name}",
        "player_err_video_output": "이 시스템에서 영상 출력을 시작할 수 없습니다.",
        "player_vo_fallback_used": "하드웨어 영상 출력에 실패하여 더 느린 대체 방식을 사용합니다.",
        "player_busy": "플레이어가 사용 중입니다. 잠시 기다려 주세요.",
        "player_tip_results_busy": "실행 중인 작업이 끝나면 결과를 열 수 있습니다",
    },
    "no": {
        "player_badge": "Spiller",
        "player_badge_ok": "Spilleren er klar (mpv {version})",
        "player_unavailable_title": "Den innebygde spilleren er ikke tilgjengelig",
        "player_missing_pymod": "Pakken python-mpv er ikke installert.",
        "player_missing_libmpv_linux": "libmpv er ikke installert. Installer den med: {cmd}",
        "player_missing_libmpv_win": "libmpv er ikke installert. Kjør setup_windows.bat (Repair), eller installer den nå.",
        "player_libmpv_too_old": "Den installerte libmpv ({version}) er for gammel: versjon 0.34 eller nyere kreves.",
        "player_libmpv_load_failed": "libmpv kunne ikke lastes inn ({detail}). Filen kan være skadet eller blokkert av antivirusprogrammet.",
        "player_vulkan_missing": "libmpv trenger Vulkan-kjøretiden (vulkan-1.dll): oppdater grafikkdriveren, eller installer spilleren på nytt.",
        "player_probe_crashed": "libmpv krasjet under innlasting: spilleren forblir deaktivert. Se loggen.",
        "player_restart_required": "Start programmet på nytt for å fullføre aktiveringen av spilleren.",
        "player_install_btn": "Installer spiller",
        "player_install_confirm": "Vil du laste ned og installere komponentene til videospilleren (ca. {size} MB)?",
        "player_installing": "Installerer spilleren...",
        "player_install_ok": "Spilleren er installert.",
        "player_install_failed": "Installasjonen av spilleren mislyktes: se loggen.",
        "player_credits": "Videoavspilling: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installasjon pågår: vent til den er ferdig.",
        "player_playlist_sources": "Kilder",
        "player_playlist_results": "Resultater",
        "player_idle_hint": "Velg en video i Inndata-listen for å forhåndsvise den her",
        "player_initializing": "Starter spilleren...",
        "player_now_playing": "Spilles nå: {name}",
        "player_nothing_loaded": "Ingen video lastet inn",
        "player_btn_playlist": "Spilleliste",
        "player_playlist_empty": "Spillelisten er tom",
        "player_tip_previous": "Forrige (P)",
        "player_tip_rewind": "10 s tilbake (venstre pil)",
        "player_tip_stop": "Stopp",
        "player_tip_play": "Spill av (mellomrom)",
        "player_tip_pause": "Pause (mellomrom)",
        "player_tip_forward": "10 s frem (høyre pil)",
        "player_tip_next": "Neste (N)",
        "player_tip_snapshot": "Lagre et bilde av gjeldende videorute (S)",
        "player_tip_open_folder": "Åpne mappen til denne videoen (O)",
        "player_tip_mute": "Demp (M)",
        "player_tip_unmute": "Slå på lyd (M)",
        "player_tip_volume": "Volum",
        "player_tip_fullscreen": "Fullskjerm (F)",
        "player_tip_exit_fullscreen": "Avslutt fullskjerm (Esc)",
        "player_snapshot_saved": "Bilde lagret: {path}",
        "player_snapshot_failed": "Bildet kunne ikke lagres",
        "player_err_load": "Denne filen kan ikke spilles av: {name}",
        "player_err_video_output": "Videoutdata kunne ikke startes på dette systemet.",
        "player_vo_fallback_used": "Maskinvarebasert videoutdata mislyktes: bruker en tregere reserve.",
        "player_busy": "Spilleren er opptatt, vennligst vent.",
        "player_tip_results_busy": "Resultater kan åpnes når den aktive jobben er ferdig",
    },
    "pl": {
        "player_badge": "Odtwarzacz",
        "player_badge_ok": "Odtwarzacz gotowy (mpv {version})",
        "player_unavailable_title": "Wbudowany odtwarzacz jest niedostępny",
        "player_missing_pymod": "Pakiet python-mpv nie jest zainstalowany.",
        "player_missing_libmpv_linux": "Biblioteka libmpv nie jest zainstalowana. Zainstaluj ją poleceniem: {cmd}",
        "player_missing_libmpv_win": "Biblioteka libmpv nie jest zainstalowana. Uruchom setup_windows.bat (Repair) lub zainstaluj ją teraz.",
        "player_libmpv_too_old": "Zainstalowana biblioteka libmpv ({version}) jest zbyt stara: wymagana jest wersja 0.34 lub nowsza.",
        "player_libmpv_load_failed": "Nie można załadować biblioteki libmpv ({detail}). Plik może być uszkodzony lub zablokowany przez program antywirusowy.",
        "player_vulkan_missing": "Biblioteka libmpv wymaga środowiska uruchomieniowego Vulkan (vulkan-1.dll): zaktualizuj sterownik karty graficznej lub zainstaluj odtwarzacz ponownie.",
        "player_probe_crashed": "Biblioteka libmpv uległa awarii podczas ładowania: odtwarzacz pozostaje wyłączony. Sprawdź dziennik.",
        "player_restart_required": "Uruchom ponownie aplikację, aby dokończyć włączanie odtwarzacza.",
        "player_install_btn": "Zainstaluj odtwarzacz",
        "player_install_confirm": "Pobrać i zainstalować składniki odtwarzacza wideo (około {size} MB)?",
        "player_installing": "Instalowanie odtwarzacza...",
        "player_install_ok": "Odtwarzacz zainstalowany.",
        "player_install_failed": "Instalacja odtwarzacza nie powiodła się: sprawdź dziennik.",
        "player_credits": "Odtwarzanie wideo: mpv (libmpv), {license}",
        "player_license_system": "biblioteka systemowa",
        "live_err_busy_install": "Trwa instalacja: poczekaj, aż się zakończy.",
        "player_playlist_sources": "Źródła",
        "player_playlist_results": "Wyniki",
        "player_idle_hint": "Wybierz film z listy Wejście, aby wyświetlić tutaj jego podgląd",
        "player_initializing": "Uruchamianie odtwarzacza...",
        "player_now_playing": "Teraz odtwarzane: {name}",
        "player_nothing_loaded": "Nie wczytano filmu",
        "player_btn_playlist": "Lista odtwarzania",
        "player_playlist_empty": "Lista odtwarzania jest pusta",
        "player_tip_previous": "Poprzedni (P)",
        "player_tip_rewind": "Cofnij o 10 s (strzałka w lewo)",
        "player_tip_stop": "Zatrzymaj",
        "player_tip_play": "Odtwórz (spacja)",
        "player_tip_pause": "Wstrzymaj (spacja)",
        "player_tip_forward": "Przewiń o 10 s (strzałka w prawo)",
        "player_tip_next": "Następny (N)",
        "player_tip_snapshot": "Zapisz zrzut bieżącej klatki (S)",
        "player_tip_open_folder": "Otwórz folder tego filmu (O)",
        "player_tip_mute": "Wycisz (M)",
        "player_tip_unmute": "Wyłącz wyciszenie (M)",
        "player_tip_volume": "Głośność",
        "player_tip_fullscreen": "Pełny ekran (F)",
        "player_tip_exit_fullscreen": "Opuść pełny ekran (Esc)",
        "player_snapshot_saved": "Zrzut zapisany: {path}",
        "player_snapshot_failed": "Nie można zapisać zrzutu",
        "player_err_load": "Nie można odtworzyć tego pliku: {name}",
        "player_err_video_output": "Nie można uruchomić wyjścia wideo w tym systemie.",
        "player_vo_fallback_used": "Sprzętowe wyjście wideo nie zadziałało: używany jest wolniejszy tryb zastępczy.",
        "player_busy": "Odtwarzacz jest zajęty, proszę czekać.",
        "player_tip_results_busy": "Wyniki można otworzyć po zakończeniu bieżącego zadania",
    },
    "pt": {
        "player_badge": "Player",
        "player_badge_ok": "Player pronto (mpv {version})",
        "player_unavailable_title": "Player integrado indisponível",
        "player_missing_pymod": "O pacote python-mpv não está instalado.",
        "player_missing_libmpv_linux": "A libmpv não está instalada. Instale-a com: {cmd}",
        "player_missing_libmpv_win": "A libmpv não está instalada. Execute setup_windows.bat (Repair) ou instale-a agora.",
        "player_libmpv_too_old": "A libmpv instalada ({version}) é antiga demais: é necessária a versão 0.34 ou mais recente.",
        "player_libmpv_load_failed": "Não foi possível carregar a libmpv ({detail}). O arquivo pode estar danificado ou bloqueado pelo antivírus.",
        "player_vulkan_missing": "A libmpv precisa do runtime Vulkan (vulkan-1.dll): atualize o driver gráfico ou instale o player novamente.",
        "player_probe_crashed": "A libmpv travou durante o carregamento: o player continua desativado. Veja o registro.",
        "player_restart_required": "Reinicie o aplicativo para concluir a ativação do player.",
        "player_install_btn": "Instalar player",
        "player_install_confirm": "Baixar e instalar os componentes do player de vídeo (cerca de {size} MB)?",
        "player_installing": "Instalando o player...",
        "player_install_ok": "Player instalado.",
        "player_install_failed": "A instalação do player falhou: veja o registro.",
        "player_credits": "Reprodução de vídeo: mpv (libmpv), {license}",
        "player_license_system": "biblioteca do sistema",
        "live_err_busy_install": "Há uma instalação em andamento: aguarde a conclusão.",
        "player_playlist_sources": "Fontes",
        "player_playlist_results": "Resultados",
        "player_idle_hint": "Selecione um vídeo na lista Entrada para o pré-visualizar aqui",
        "player_initializing": "A iniciar o leitor...",
        "player_now_playing": "A reproduzir: {name}",
        "player_nothing_loaded": "Nenhum vídeo carregado",
        "player_btn_playlist": "Lista de reprodução",
        "player_playlist_empty": "A lista de reprodução está vazia",
        "player_tip_previous": "Anterior (P)",
        "player_tip_rewind": "Recuar 10 s (seta esquerda)",
        "player_tip_stop": "Parar",
        "player_tip_play": "Reproduzir (espaço)",
        "player_tip_pause": "Pausa (espaço)",
        "player_tip_forward": "Avançar 10 s (seta direita)",
        "player_tip_next": "Seguinte (N)",
        "player_tip_snapshot": "Guardar uma captura do fotograma atual (S)",
        "player_tip_open_folder": "Abrir a pasta deste vídeo (O)",
        "player_tip_mute": "Silenciar (M)",
        "player_tip_unmute": "Ativar som (M)",
        "player_tip_volume": "Volume",
        "player_tip_fullscreen": "Ecrã inteiro (F)",
        "player_tip_exit_fullscreen": "Sair do ecrã inteiro (Esc)",
        "player_snapshot_saved": "Captura guardada: {path}",
        "player_snapshot_failed": "Não foi possível guardar a captura",
        "player_err_load": "Não é possível reproduzir este ficheiro: {name}",
        "player_err_video_output": "Não foi possível iniciar a saída de vídeo neste sistema.",
        "player_vo_fallback_used": "A saída de vídeo por hardware falhou: será usada uma alternativa mais lenta.",
        "player_busy": "O leitor está ocupado, aguarde.",
        "player_tip_results_busy": "Os resultados podem ser abertos quando a tarefa em curso terminar",
    },
    "ro": {
        "player_badge": "Player",
        "player_badge_ok": "Playerul este pregătit (mpv {version})",
        "player_unavailable_title": "Playerul integrat nu este disponibil",
        "player_missing_pymod": "Pachetul python-mpv nu este instalat.",
        "player_missing_libmpv_linux": "libmpv nu este instalată. Instalați-o cu: {cmd}",
        "player_missing_libmpv_win": "libmpv nu este instalată. Rulați setup_windows.bat (Repair) sau instalați-o acum.",
        "player_libmpv_too_old": "libmpv instalată ({version}) este prea veche: este necesară versiunea 0.34 sau mai nouă.",
        "player_libmpv_load_failed": "libmpv nu a putut fi încărcată ({detail}). Fișierul poate fi deteriorat sau blocat de antivirus.",
        "player_vulkan_missing": "libmpv are nevoie de mediul de rulare Vulkan (vulkan-1.dll): actualizați driverul plăcii grafice sau reinstalați playerul.",
        "player_probe_crashed": "libmpv s-a oprit neașteptat în timpul încărcării: playerul rămâne dezactivat. Consultați jurnalul.",
        "player_restart_required": "Reporniți aplicația pentru a finaliza activarea playerului.",
        "player_install_btn": "Instalează playerul",
        "player_install_confirm": "Descărcați și instalați componentele playerului video (aproximativ {size} MB)?",
        "player_installing": "Se instalează playerul...",
        "player_install_ok": "Playerul a fost instalat.",
        "player_install_failed": "Instalarea playerului a eșuat: consultați jurnalul.",
        "player_credits": "Redare video: mpv (libmpv), {license}",
        "player_license_system": "bibliotecă de sistem",
        "live_err_busy_install": "O instalare este în curs: așteptați să se termine.",
        "player_playlist_sources": "Surse",
        "player_playlist_results": "Rezultate",
        "player_idle_hint": "Selectați un videoclip din lista Intrare pentru a-l previzualiza aici",
        "player_initializing": "Se pornește playerul...",
        "player_now_playing": "Se redă acum: {name}",
        "player_nothing_loaded": "Niciun videoclip încărcat",
        "player_btn_playlist": "Listă de redare",
        "player_playlist_empty": "Lista de redare este goală",
        "player_tip_previous": "Anterior (P)",
        "player_tip_rewind": "Înapoi 10 s (săgeată stânga)",
        "player_tip_stop": "Oprire",
        "player_tip_play": "Redare (spațiu)",
        "player_tip_pause": "Pauză (spațiu)",
        "player_tip_forward": "Înainte 10 s (săgeată dreapta)",
        "player_tip_next": "Următor (N)",
        "player_tip_snapshot": "Salvează o captură a cadrului curent (S)",
        "player_tip_open_folder": "Deschide folderul acestui videoclip (O)",
        "player_tip_mute": "Dezactivează sunetul (M)",
        "player_tip_unmute": "Activează sunetul (M)",
        "player_tip_volume": "Volum",
        "player_tip_fullscreen": "Ecran complet (F)",
        "player_tip_exit_fullscreen": "Ieși din ecranul complet (Esc)",
        "player_snapshot_saved": "Captură salvată: {path}",
        "player_snapshot_failed": "Captura nu a putut fi salvată",
        "player_err_load": "Acest fișier nu poate fi redat: {name}",
        "player_err_video_output": "Ieșirea video nu a putut porni pe acest sistem.",
        "player_vo_fallback_used": "Ieșirea video hardware a eșuat: se folosește o alternativă mai lentă.",
        "player_busy": "Playerul este ocupat, așteptați.",
        "player_tip_results_busy": "Rezultatele pot fi deschise după terminarea sarcinii în curs",
    },
    "ru": {
        "player_badge": "Плеер",
        "player_badge_ok": "Плеер готов (mpv {version})",
        "player_unavailable_title": "Встроенный плеер недоступен",
        "player_missing_pymod": "Пакет python-mpv не установлен.",
        "player_missing_libmpv_linux": "libmpv не установлена. Установите её командой: {cmd}",
        "player_missing_libmpv_win": "libmpv не установлена. Запустите setup_windows.bat (Repair) или установите её сейчас.",
        "player_libmpv_too_old": "Установленная libmpv ({version}) слишком старая: нужна версия 0.34 или новее.",
        "player_libmpv_load_failed": "Не удалось загрузить libmpv ({detail}). Возможно, файл повреждён или заблокирован антивирусом.",
        "player_vulkan_missing": "Для libmpv нужна среда выполнения Vulkan (vulkan-1.dll): обновите драйвер видеокарты или установите плеер заново.",
        "player_probe_crashed": "libmpv аварийно завершилась при загрузке: плеер остаётся отключённым. См. журнал.",
        "player_restart_required": "Перезапустите приложение, чтобы завершить включение плеера.",
        "player_install_btn": "Установить плеер",
        "player_install_confirm": "Скачать и установить компоненты видеоплеера (около {size} МБ)?",
        "player_installing": "Установка плеера...",
        "player_install_ok": "Плеер установлен.",
        "player_install_failed": "Не удалось установить плеер: см. журнал.",
        "player_credits": "Воспроизведение видео: mpv (libmpv), {license}",
        "player_license_system": "системная библиотека",
        "live_err_busy_install": "Идёт установка: дождитесь её завершения.",
        "player_playlist_sources": "Исходные файлы",
        "player_playlist_results": "Результаты",
        "player_idle_hint": "Выберите видео в списке «Входные файлы», чтобы просмотреть его здесь",
        "player_initializing": "Запуск плеера...",
        "player_now_playing": "Сейчас воспроизводится: {name}",
        "player_nothing_loaded": "Видео не загружено",
        "player_btn_playlist": "Список воспроизведения",
        "player_playlist_empty": "Список воспроизведения пуст",
        "player_tip_previous": "Предыдущее (P)",
        "player_tip_rewind": "Назад на 10 с (стрелка влево)",
        "player_tip_stop": "Остановить",
        "player_tip_play": "Воспроизвести (пробел)",
        "player_tip_pause": "Пауза (пробел)",
        "player_tip_forward": "Вперёд на 10 с (стрелка вправо)",
        "player_tip_next": "Следующее (N)",
        "player_tip_snapshot": "Сохранить снимок текущего кадра (S)",
        "player_tip_open_folder": "Открыть папку этого видео (O)",
        "player_tip_mute": "Отключить звук (M)",
        "player_tip_unmute": "Включить звук (M)",
        "player_tip_volume": "Громкость",
        "player_tip_fullscreen": "Полный экран (F)",
        "player_tip_exit_fullscreen": "Выйти из полноэкранного режима (Esc)",
        "player_snapshot_saved": "Снимок сохранён: {path}",
        "player_snapshot_failed": "Не удалось сохранить снимок",
        "player_err_load": "Не удалось воспроизвести этот файл: {name}",
        "player_err_video_output": "Не удалось запустить вывод видео в этой системе.",
        "player_vo_fallback_used": "Аппаратный вывод видео не удался: используется более медленный резервный режим.",
        "player_busy": "Плеер занят, подождите.",
        "player_tip_results_busy": "Результаты можно открыть после завершения текущей задачи",
    },
    "es": {
        "player_badge": "Reproductor",
        "player_badge_ok": "Reproductor listo (mpv {version})",
        "player_unavailable_title": "Reproductor integrado no disponible",
        "player_missing_pymod": "El paquete python-mpv no está instalado.",
        "player_missing_libmpv_linux": "libmpv no está instalada. Instálala con: {cmd}",
        "player_missing_libmpv_win": "libmpv no está instalada. Ejecuta setup_windows.bat (Repair) o instálala ahora.",
        "player_libmpv_too_old": "La libmpv instalada ({version}) es demasiado antigua: se necesita la versión 0.34 o posterior.",
        "player_libmpv_load_failed": "No se pudo cargar libmpv ({detail}). Puede que el archivo esté dañado o bloqueado por el antivirus.",
        "player_vulkan_missing": "libmpv necesita el runtime de Vulkan (vulkan-1.dll): actualiza el controlador gráfico o vuelve a instalar el reproductor.",
        "player_probe_crashed": "libmpv se bloqueó durante la carga: el reproductor sigue desactivado. Consulta el registro.",
        "player_restart_required": "Reinicia la aplicación para terminar de activar el reproductor.",
        "player_install_btn": "Instalar reproductor",
        "player_install_confirm": "¿Descargar e instalar los componentes del reproductor de vídeo (unos {size} MB)?",
        "player_installing": "Instalando el reproductor...",
        "player_install_ok": "Reproductor instalado.",
        "player_install_failed": "La instalación del reproductor falló: consulta el registro.",
        "player_credits": "Reproducción de vídeo: mpv (libmpv), {license}",
        "player_license_system": "biblioteca del sistema",
        "live_err_busy_install": "Hay una instalación en curso: espera a que termine.",
        "player_playlist_sources": "Fuentes",
        "player_playlist_results": "Resultados",
        "player_idle_hint": "Selecciona un vídeo de la lista Entrada para previsualizarlo aquí",
        "player_initializing": "Iniciando el reproductor...",
        "player_now_playing": "Reproduciendo: {name}",
        "player_nothing_loaded": "No hay ningún vídeo cargado",
        "player_btn_playlist": "Lista de reproducción",
        "player_playlist_empty": "La lista de reproducción está vacía",
        "player_tip_previous": "Anterior (P)",
        "player_tip_rewind": "Retroceder 10 s (flecha izquierda)",
        "player_tip_stop": "Detener",
        "player_tip_play": "Reproducir (espacio)",
        "player_tip_pause": "Pausa (espacio)",
        "player_tip_forward": "Avanzar 10 s (flecha derecha)",
        "player_tip_next": "Siguiente (N)",
        "player_tip_snapshot": "Guardar una captura del fotograma actual (S)",
        "player_tip_open_folder": "Abrir la carpeta de este vídeo (O)",
        "player_tip_mute": "Silenciar (M)",
        "player_tip_unmute": "Activar sonido (M)",
        "player_tip_volume": "Volumen",
        "player_tip_fullscreen": "Pantalla completa (F)",
        "player_tip_exit_fullscreen": "Salir de pantalla completa (Esc)",
        "player_snapshot_saved": "Captura guardada: {path}",
        "player_snapshot_failed": "No se pudo guardar la captura",
        "player_err_load": "No se puede reproducir este archivo: {name}",
        "player_err_video_output": "No se pudo iniciar la salida de vídeo en este sistema.",
        "player_vo_fallback_used": "Falló la salida de vídeo por hardware: se usará una alternativa más lenta.",
        "player_busy": "El reproductor está ocupado, espera.",
        "player_tip_results_busy": "Los resultados se pueden abrir cuando termine la tarea en curso",
    },
    "sv": {
        "player_badge": "Spelare",
        "player_badge_ok": "Spelaren är redo (mpv {version})",
        "player_unavailable_title": "Den inbyggda spelaren är inte tillgänglig",
        "player_missing_pymod": "Paketet python-mpv är inte installerat.",
        "player_missing_libmpv_linux": "libmpv är inte installerat. Installera det med: {cmd}",
        "player_missing_libmpv_win": "libmpv är inte installerat. Kör setup_windows.bat (Repair) eller installera det nu.",
        "player_libmpv_too_old": "Den installerade libmpv ({version}) är för gammal: version 0.34 eller senare krävs.",
        "player_libmpv_load_failed": "libmpv kunde inte läsas in ({detail}). Filen kan vara skadad eller blockerad av antivirusprogrammet.",
        "player_vulkan_missing": "libmpv behöver Vulkan-körmiljön (vulkan-1.dll): uppdatera grafikdrivrutinen eller installera om spelaren.",
        "player_probe_crashed": "libmpv kraschade vid inläsningen: spelaren förblir inaktiverad. Se loggen.",
        "player_restart_required": "Starta om programmet för att slutföra aktiveringen av spelaren.",
        "player_install_btn": "Installera spelare",
        "player_install_confirm": "Vill du hämta och installera videospelarens komponenter (cirka {size} MB)?",
        "player_installing": "Installerar spelaren...",
        "player_install_ok": "Spelaren är installerad.",
        "player_install_failed": "Installationen av spelaren misslyckades: se loggen.",
        "player_credits": "Videouppspelning: mpv (libmpv), {license}",
        "player_license_system": "systembibliotek",
        "live_err_busy_install": "En installation pågår: vänta tills den är klar.",
        "player_playlist_sources": "Källor",
        "player_playlist_results": "Resultat",
        "player_idle_hint": "Välj en video i listan Indata för att förhandsgranska den här",
        "player_initializing": "Startar spelaren...",
        "player_now_playing": "Spelas nu: {name}",
        "player_nothing_loaded": "Ingen video har lästs in",
        "player_btn_playlist": "Spellista",
        "player_playlist_empty": "Spellistan är tom",
        "player_tip_previous": "Föregående (P)",
        "player_tip_rewind": "10 s bakåt (vänsterpil)",
        "player_tip_stop": "Stoppa",
        "player_tip_play": "Spela (blanksteg)",
        "player_tip_pause": "Pausa (blanksteg)",
        "player_tip_forward": "10 s framåt (högerpil)",
        "player_tip_next": "Nästa (N)",
        "player_tip_snapshot": "Spara en bild av den aktuella bildrutan (S)",
        "player_tip_open_folder": "Öppna mappen för den här videon (O)",
        "player_tip_mute": "Stäng av ljudet (M)",
        "player_tip_unmute": "Slå på ljudet (M)",
        "player_tip_volume": "Volym",
        "player_tip_fullscreen": "Helskärm (F)",
        "player_tip_exit_fullscreen": "Lämna helskärmsläge (Esc)",
        "player_snapshot_saved": "Bilden sparades: {path}",
        "player_snapshot_failed": "Bilden kunde inte sparas",
        "player_err_load": "Filen kan inte spelas upp: {name}",
        "player_err_video_output": "Videoutmatningen kunde inte startas på det här systemet.",
        "player_vo_fallback_used": "Maskinvarubaserad videoutmatning misslyckades: ett långsammare reservläge används.",
        "player_busy": "Spelaren är upptagen, vänta.",
        "player_tip_results_busy": "Resultaten kan öppnas när det pågående jobbet är klart",
    },
    "tr": {
        "player_badge": "Oynatıcı",
        "player_badge_ok": "Oynatıcı hazır (mpv {version})",
        "player_unavailable_title": "Yerleşik oynatıcı kullanılamıyor",
        "player_missing_pymod": "python-mpv paketi yüklü değil.",
        "player_missing_libmpv_linux": "libmpv yüklü değil. Şu komutla yükleyin: {cmd}",
        "player_missing_libmpv_win": "libmpv yüklü değil. setup_windows.bat (Repair) çalıştırın veya şimdi yükleyin.",
        "player_libmpv_too_old": "Yüklü libmpv ({version}) çok eski: 0.34 veya daha yeni bir sürüm gerekiyor.",
        "player_libmpv_load_failed": "libmpv yüklenemedi ({detail}). Dosya bozuk olabilir veya virüsten koruma yazılımı tarafından engellenmiş olabilir.",
        "player_vulkan_missing": "libmpv, Vulkan çalışma zamanına (vulkan-1.dll) ihtiyaç duyuyor: grafik sürücüsünü güncelleyin veya oynatıcıyı yeniden yükleyin.",
        "player_probe_crashed": "libmpv yüklenirken çöktü: oynatıcı devre dışı kalıyor. Günlüğe bakın.",
        "player_restart_required": "Oynatıcının etkinleştirilmesini tamamlamak için uygulamayı yeniden başlatın.",
        "player_install_btn": "Oynatıcıyı yükle",
        "player_install_confirm": "Video oynatıcı bileşenleri indirilip yüklensin mi (yaklaşık {size} MB)?",
        "player_installing": "Oynatıcı yükleniyor...",
        "player_install_ok": "Oynatıcı yüklendi.",
        "player_install_failed": "Oynatıcı yüklenemedi: günlüğe bakın.",
        "player_credits": "Video oynatma: mpv (libmpv), {license}",
        "player_license_system": "sistem kitaplığı",
        "live_err_busy_install": "Bir yükleme devam ediyor: bitmesini bekleyin.",
        "player_playlist_sources": "Kaynaklar",
        "player_playlist_results": "Sonuçlar",
        "player_idle_hint": "Burada önizlemek için Giriş listesinden bir video seçin",
        "player_initializing": "Oynatıcı başlatılıyor...",
        "player_now_playing": "Şimdi oynatılıyor: {name}",
        "player_nothing_loaded": "Video yüklenmedi",
        "player_btn_playlist": "Oynatma listesi",
        "player_playlist_empty": "Oynatma listesi boş",
        "player_tip_previous": "Önceki (P)",
        "player_tip_rewind": "10 sn geri (sol ok)",
        "player_tip_stop": "Durdur",
        "player_tip_play": "Oynat (boşluk)",
        "player_tip_pause": "Duraklat (boşluk)",
        "player_tip_forward": "10 sn ileri (sağ ok)",
        "player_tip_next": "Sonraki (N)",
        "player_tip_snapshot": "Geçerli karenin görüntüsünü kaydet (S)",
        "player_tip_open_folder": "Bu videonun klasörünü aç (O)",
        "player_tip_mute": "Sesi kapat (M)",
        "player_tip_unmute": "Sesi aç (M)",
        "player_tip_volume": "Ses düzeyi",
        "player_tip_fullscreen": "Tam ekran (F)",
        "player_tip_exit_fullscreen": "Tam ekrandan çık (Esc)",
        "player_snapshot_saved": "Görüntü kaydedildi: {path}",
        "player_snapshot_failed": "Görüntü kaydedilemedi",
        "player_err_load": "Bu dosya oynatılamıyor: {name}",
        "player_err_video_output": "Bu sistemde video çıkışı başlatılamadı.",
        "player_vo_fallback_used": "Donanım video çıkışı başarısız oldu: daha yavaş bir yedek kullanılıyor.",
        "player_busy": "Oynatıcı meşgul, lütfen bekleyin.",
        "player_tip_results_busy": "Sonuçlar, devam eden iş tamamlandığında açılabilir",
    },
    "uk": {
        "player_badge": "Плеєр",
        "player_badge_ok": "Плеєр готовий (mpv {version})",
        "player_unavailable_title": "Вбудований плеєр недоступний",
        "player_missing_pymod": "Пакет python-mpv не встановлено.",
        "player_missing_libmpv_linux": "libmpv не встановлено. Встановіть її командою: {cmd}",
        "player_missing_libmpv_win": "libmpv не встановлено. Запустіть setup_windows.bat (Repair) або встановіть її зараз.",
        "player_libmpv_too_old": "Встановлена libmpv ({version}) занадто стара: потрібна версія 0.34 або новіша.",
        "player_libmpv_load_failed": "Не вдалося завантажити libmpv ({detail}). Можливо, файл пошкоджено або заблоковано антивірусом.",
        "player_vulkan_missing": "Для libmpv потрібне середовище виконання Vulkan (vulkan-1.dll): оновіть драйвер відеокарти або встановіть плеєр знову.",
        "player_probe_crashed": "libmpv аварійно завершила роботу під час завантаження: плеєр залишається вимкненим. Див. журнал.",
        "player_restart_required": "Перезапустіть застосунок, щоб завершити увімкнення плеєра.",
        "player_install_btn": "Встановити плеєр",
        "player_install_confirm": "Завантажити та встановити компоненти відеоплеєра (близько {size} МБ)?",
        "player_installing": "Встановлення плеєра...",
        "player_install_ok": "Плеєр встановлено.",
        "player_install_failed": "Не вдалося встановити плеєр: див. журнал.",
        "player_credits": "Відтворення відео: mpv (libmpv), {license}",
        "player_license_system": "системна бібліотека",
        "live_err_busy_install": "Триває встановлення: зачекайте, доки воно завершиться.",
        "player_playlist_sources": "Джерела",
        "player_playlist_results": "Результати",
        "player_idle_hint": "Виберіть відео у списку вхідних файлів, щоб переглянути його тут",
        "player_initializing": "Запуск плеєра...",
        "player_now_playing": "Зараз відтворюється: {name}",
        "player_nothing_loaded": "Відео не завантажено",
        "player_btn_playlist": "Список відтворення",
        "player_playlist_empty": "Список відтворення порожній",
        "player_tip_previous": "Попереднє (P)",
        "player_tip_rewind": "Назад на 10 с (стрілка ліворуч)",
        "player_tip_stop": "Зупинити",
        "player_tip_play": "Відтворити (пробіл)",
        "player_tip_pause": "Пауза (пробіл)",
        "player_tip_forward": "Уперед на 10 с (стрілка праворуч)",
        "player_tip_next": "Наступне (N)",
        "player_tip_snapshot": "Зберегти знімок поточного кадру (S)",
        "player_tip_open_folder": "Відкрити папку цього відео (O)",
        "player_tip_mute": "Вимкнути звук (M)",
        "player_tip_unmute": "Увімкнути звук (M)",
        "player_tip_volume": "Гучність",
        "player_tip_fullscreen": "Повний екран (F)",
        "player_tip_exit_fullscreen": "Вийти з повноекранного режиму (Esc)",
        "player_snapshot_saved": "Знімок збережено: {path}",
        "player_snapshot_failed": "Не вдалося зберегти знімок",
        "player_err_load": "Не вдалося відтворити цей файл: {name}",
        "player_err_video_output": "Не вдалося запустити відеовихід у цій системі.",
        "player_vo_fallback_used": "Апаратний відеовихід не спрацював: використовується повільніший резервний режим.",
        "player_busy": "Плеєр зайнятий, зачекайте.",
        "player_tip_results_busy": "Результати можна відкрити після завершення поточного завдання",
    },
    "vi": {
        "player_badge": "Trình phát",
        "player_badge_ok": "Trình phát đã sẵn sàng (mpv {version})",
        "player_unavailable_title": "Trình phát tích hợp không khả dụng",
        "player_missing_pymod": "Gói python-mpv chưa được cài đặt.",
        "player_missing_libmpv_linux": "libmpv chưa được cài đặt. Hãy cài đặt bằng lệnh: {cmd}",
        "player_missing_libmpv_win": "libmpv chưa được cài đặt. Hãy chạy setup_windows.bat (Repair) hoặc cài đặt ngay.",
        "player_libmpv_too_old": "libmpv đã cài đặt ({version}) quá cũ: cần phiên bản 0.34 trở lên.",
        "player_libmpv_load_failed": "Không thể tải libmpv ({detail}). Tệp có thể bị hỏng hoặc bị phần mềm diệt virus chặn.",
        "player_vulkan_missing": "libmpv cần môi trường chạy Vulkan (vulkan-1.dll): hãy cập nhật trình điều khiển đồ họa hoặc cài đặt lại trình phát.",
        "player_probe_crashed": "libmpv bị lỗi khi tải: trình phát vẫn bị tắt. Xem nhật ký.",
        "player_restart_required": "Hãy khởi động lại ứng dụng để hoàn tất việc bật trình phát.",
        "player_install_btn": "Cài đặt trình phát",
        "player_install_confirm": "Tải xuống và cài đặt các thành phần của trình phát video (khoảng {size} MB)?",
        "player_installing": "Đang cài đặt trình phát...",
        "player_install_ok": "Đã cài đặt trình phát.",
        "player_install_failed": "Cài đặt trình phát thất bại: xem nhật ký.",
        "player_credits": "Phát video: mpv (libmpv), {license}",
        "player_license_system": "thư viện hệ thống",
        "live_err_busy_install": "Đang có một quá trình cài đặt: hãy chờ đến khi hoàn tất.",
        "player_playlist_sources": "Nguồn",
        "player_playlist_results": "Kết quả",
        "player_idle_hint": "Chọn một video trong danh sách Đầu vào để xem trước tại đây",
        "player_initializing": "Đang khởi động trình phát...",
        "player_now_playing": "Đang phát: {name}",
        "player_nothing_loaded": "Chưa tải video",
        "player_btn_playlist": "Danh sách phát",
        "player_playlist_empty": "Danh sách phát đang trống",
        "player_tip_previous": "Trước (P)",
        "player_tip_rewind": "Lùi 10 giây (mũi tên trái)",
        "player_tip_stop": "Dừng",
        "player_tip_play": "Phát (phím cách)",
        "player_tip_pause": "Tạm dừng (phím cách)",
        "player_tip_forward": "Tiến 10 giây (mũi tên phải)",
        "player_tip_next": "Tiếp theo (N)",
        "player_tip_snapshot": "Lưu ảnh của khung hình hiện tại (S)",
        "player_tip_open_folder": "Mở thư mục của video này (O)",
        "player_tip_mute": "Tắt tiếng (M)",
        "player_tip_unmute": "Bật tiếng (M)",
        "player_tip_volume": "Âm lượng",
        "player_tip_fullscreen": "Toàn màn hình (F)",
        "player_tip_exit_fullscreen": "Thoát toàn màn hình (Esc)",
        "player_snapshot_saved": "Đã lưu ảnh: {path}",
        "player_snapshot_failed": "Không thể lưu ảnh",
        "player_err_load": "Không thể phát tệp này: {name}",
        "player_err_video_output": "Không thể khởi động đầu ra video trên hệ thống này.",
        "player_vo_fallback_used": "Đầu ra video phần cứng không thành công: đang dùng phương án dự phòng chậm hơn.",
        "player_busy": "Trình phát đang bận, vui lòng chờ.",
        "player_tip_results_busy": "Có thể mở kết quả khi tác vụ đang chạy kết thúc",
    },
}

# P3 settings labels, localized for every supported interface language.
_P3_SETTINGS_STRINGS = {
    "ar": ("المشغل", "تحميل الفيديوهات المترجمة تلقائيًا في المشغل", "إضافة الصوت الأصلي كمسار بديل"),
    "zh": ("播放器", "自动在播放器中加载已翻译视频", "将原始音频作为备用音轨加入"),
    "cs": ("Přehrávač", "Automaticky načítat přeložená videa do přehrávače", "Přidat původní zvuk jako alternativní stopu"),
    "da": ("Afspiller", "Indlæs automatisk oversatte videoer i afspilleren", "Medtag original lyd som et alternativt lydspor"),
    "nl": ("Speler", "Vertaalde video's automatisch in de speler laden", "Originele audio als alternatieve audiotrack toevoegen"),
    "fi": ("Soitin", "Lataa käännetyt videot automaattisesti soittimeen", "Sisällytä alkuperäinen ääni vaihtoehtoisena ääniraitana"),
    "fr": ("Lecteur", "Charger automatiquement les vidéos traduites dans le lecteur", "Inclure l’audio original comme piste alternative"),
    "de": ("Player", "Übersetzte Videos automatisch im Player laden", "Originalton als alternative Audiospur hinzufügen"),
    "el": ("Πρόγραμμα αναπαραγωγής", "Αυτόματη φόρτωση μεταφρασμένων βίντεο", "Συμπερίληψη του αρχικού ήχου ως εναλλακτικού κομματιού"),
    "hi": ("प्लेयर", "अनुवादित वीडियो प्लेयर में अपने आप खोलें", "मूल ऑडियो को वैकल्पिक ट्रैक के रूप में शामिल करें"),
    "hu": ("Lejátszó", "Lefordított videók automatikus betöltése a lejátszóba", "Eredeti hang hozzáadása alternatív hangsávként"),
    "id": ("Pemutar", "Muat video terjemahan secara otomatis ke pemutar", "Sertakan audio asli sebagai trek alternatif"),
    "ja": ("プレーヤー", "翻訳済み動画をプレーヤーに自動読み込み", "元の音声を別の音声トラックとして含める"),
    "ko": ("플레이어", "번역된 동영상을 플레이어에 자동으로 불러오기", "원본 오디오를 대체 오디오 트랙으로 포함"),
    "no": ("Spiller", "Last oversatte videoer automatisk inn i spilleren", "Ta med original lyd som et alternativt lydspor"),
    "pl": ("Odtwarzacz", "Automatycznie wczytuj przetłumaczone filmy do odtwarzacza", "Dołącz oryginalny dźwięk jako alternatywną ścieżkę"),
    "pt": ("Reprodutor", "Carregar automaticamente vídeos traduzidos no reprodutor", "Incluir o áudio original como faixa alternativa"),
    "ro": ("Player", "Încarcă automat videoclipurile traduse în player", "Include sunetul original ca pistă audio alternativă"),
    "ru": ("Плеер", "Автоматически загружать переведённые видео в плеер", "Добавлять оригинальный звук как альтернативную дорожку"),
    "es": ("Reproductor", "Cargar automáticamente los vídeos traducidos en el reproductor", "Incluir el audio original como pista alternativa"),
    "sv": ("Spelare", "Läs in översatta videor automatiskt i spelaren", "Ta med originalljud som ett alternativt ljudspår"),
    "tr": ("Oynatıcı", "Çevrilen videoları oynatıcıya otomatik yükle", "Orijinal sesi alternatif bir ses parçası olarak ekle"),
    "uk": ("Програвач", "Автоматично завантажувати перекладені відео", "Додавати оригінальний звук як альтернативну доріжку"),
    "vi": ("Trình phát", "Tự động tải video đã dịch vào trình phát", "Thêm âm thanh gốc làm bản âm thanh thay thế"),
}
for _lang, (_section, _autoload, _original) in _P3_SETTINGS_STRINGS.items():
    PLAYER_UI_STRINGS[_lang].update({
        "settings_player": _section,
        "opt_player_autoload": _autoload,
        "opt_keep_original_audio": _original,
    })

PLAYER_KEYS: tuple[str, ...] = tuple(sorted(PLAYER_UI_STRINGS["en"]))


def merge_into(ui_strings: dict[str, dict[str, str]]) -> list[str]:
    """Add the player strings to ``ui_strings`` in place and return the problems found.

    Never raises (spec 2.6, [CC] G27): a key that already exists with a
    different value keeps the existing value and is reported as
    ``"collision <lang>.<key>"``; a language the target does not have is
    skipped and reported as ``"unknown language '<lang>'"``. Merging twice is
    harmless (equal values are not collisions).
    """
    problems: list[str] = []
    for lang, entries in PLAYER_UI_STRINGS.items():
        bucket = ui_strings.get(lang)
        if bucket is None:
            problems.append(f"unknown language {lang!r}")
            continue
        for key, value in entries.items():
            existing = bucket.get(key)
            if existing is not None and existing != value:
                problems.append(f"collision {lang}.{key}")
                continue
            bucket[key] = value
    return problems
